### DISCUSSION TITLE
// +kubebuilder:pruning:PreserveUnknownFields on array field

### DISCUSSION THREAD

**Discussion by leviisfool** [kubernetes-sigs/kubebuilder#2178] [Support] [answered]
Struct definition: `// +kubebuilder:pruning:PreserveUnknownFields` on array field
```go
type Status struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	Deployed   []unstructured.Unstructured `json:"deployed,omitempty"`
}
```
Generated:  `x-kubernetes-preserve-unknown-fields: true` under deployed
```yaml
deployed:
  items:
    type: object
  type: array
  x-kubernetes-preserve-unknown-fields: true
```
Expect:  `x-kubernetes-preserve-unknown-fields: true` under items
```yaml
deployed: 
  items:
    type: object
    x-kubernetes-preserve-unknown-fields: true
  type: array
```

**Is there a way to generate `x-kubernetes-preserve-unknown-fields: true` under items for a array field?**
