### DISCUSSION TITLE
`// +kubebuilder:rbac` Generates ClusterRole with name "manager-role", How to change this name ?.

### DISCUSSION THREAD

**Discussion by SAbdulRahuman** [kubernetes-sigs/kubebuilder#2297] [Support] [answered]
Hi ,
I'm using `+kubebuilder` markers to generate RBAC ClusterRoles, for example below are the markers i have created

```yaml
// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=apps,resources=replicasets,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=pods,verbs=get;list;watch;create;
// +kubebuilder:rbac:groups=core,resources=services,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=configmaps,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=serviceaccounts,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=configmaps,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=replicasets,verbs=get;list;watch;create;update;patch;delete
```
 
Kubebuilder generated ClusterRole `role.yaml` with name as `manager-role` but i want to different name. How to mentioned kubebuilder to generate the ClusterRole with differrrent name ?

For example, Below the ClusterRole got generated

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

My question is, How to change `name: manager-role` to `  name: test-role`
