### DISCUSSION TITLE
Conversion webhook path failure with "the server could not find the requested resource"

### DISCUSSION THREAD

**Discussion by tpiperatgod** [kubernetes-sigs/kubebuilder#2351] [Support] [answered]
Hi, I'm having a problem with the webhook marker (referenced in [Tutorial: Multi-Version API - The Kubebuilder Book](https://kubebuilder.io/multiversion-tutorial/tutorial.html)).

## Environment
```shell
~# kubebuilder version
Version: main.version{KubeBuilderVersion:"3.1.0", KubernetesVendor:"1.19.2", GitCommit:"92e0349ca7334a0a8e5e499da4fb077eb524e94a", BuildDate:"2021-05-27T17:54:28Z", GoOs:"linux", GoArch:"amd64"}

~# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

~# go version
go version go1.16.7 linux/amd64

controller-runtime - v0.8.3
```

## Issue Description
I use the operator to maintain two versions of CRDs, where v1alpha1 is the hub and v1alpha2 is the spoke and set `storageversion`.

Then I set up the conversion file (both in v1alpha1 and v1alpha2) and the webhook file (in v1alpha2). In the webhook file, I set a webhook marker: `//+kubebuilder:webhook:path=/{my_path}`(I assume it is `/{my_path}`.)

Then I made the corresponding configuration in `crd/patches/webhook_in_resources.yaml`, and I used `url` instead of `service` in the following.

```yaml
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        url: "https://<my_operator_server_address>:9443/{my_path}"
        caBundle: {ca content with base64 encoded}
      conversionReviewVersions:
      - v1
```

However, when creating the v1alpha1 resource, the following error message appears.

```shell
Error from server: error when creating "resource.yaml": conversion webhook for resource.io/v1alpha1, Kind=Test failed: the server could not find the requested resource
```

Then I changed `/{my_path}` to `/convert` and everything works fine.

Is there something wrong with the `//+kubebuilder:webhook:path=/{my_path}` marker, or am I missing something?

Thx!
