### DISCUSSION TITLE
Does Kubebuilder Annotation support NamespaceSelector?

### DISCUSSION THREAD

**Discussion by moluzhui** [kubernetes-sigs/kubebuilder#2461] [Support] [answered]
Can [kubebuilder_annotation](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/kubebuilder_annotation.md) support the following namespace configuration?
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutate-config
webhooks:
- name: mutate-config
  clientConfig:
    service:
      name: webhook-server
      namespace: default
      path: "/mutate-pod"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
      matchLabels:
        mutate-pod: true
```
