### DISCUSSION TITLE
How could I differ oldDeployment and newDeployment is the equal

### DISCUSSION THREAD

**Discussion by mingregister** [kubernetes-sigs/kubebuilder#2515] [Support] [answered]
Suppose I have a controller, which used to control the deployment, such as the following yaml file.
```
apiVersion: myDeploymentCrontroller.com/v1beta1
kind: MyDeploymentCrontroller
metadata:
  name: myDeploymentCrontroller-sample
  namespace: default
spec:
  image: nginx:alpine
  ports:
    - port: 80

```
The above yaml file will create a deployment, named myDeploymentCrontroller-sample and with port: 80, image: nginx:alpine (let's call this  version1)

After myDeploymentCrontroller created the deployment, somebody modify the deployment with the cmd: kubectl edit deploy myDeploymentCrontroller-sample (let's call this version2)

My question is how could I distinguish version2 and version1 is equal with myDeploymentCrontroller code, so that I can decide whether to call r.Client.Update() method to update the deployment.
