### DISCUSSION TITLE
CRD Multiversion (Conversion webhook)

### DISCUSSION THREAD

**Discussion by serhermar** [kubernetes-sigs/kubebuilder#2533] [Support] [answered]
Hello everyone,

I am developing an operator with kubebuilder 3.2.0, I am looking at the possibility of using multiversion and I have encountered a problem.

By adding the following to the CRD itself for the convert webhook:

```
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: webhook-service
          namespace: system
          path: /convert
      conversionReviewVersions:
      - v1
```

This makes the operator have to be cluster-wide, since the CRD is the one that marks which is the webhook-server.

I have seen the possibility of setting strategy: None, but of course the conversion method to the hub version is not executed.

I am doing something wrong? o Is there an alternative to not force the operator to be cluster-wide but namespace-wide?

Thank you very much in advance
