### DISCUSSION TITLE
Nested defaults

### DISCUSSION THREAD

**Discussion by tbarizien** [kubernetes-sigs/kubebuilder#3208] [Support] [answered]
Hi,

I've been investigating the way defaulting annotations work following a series of strange behaviour occurences in the operators I'm maintaining. We were making a series of small mistakes not following the [k8s api conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required) regarding optional fields but after fixing this, I'm still wondering about the following use case:

I've made a [dummy project](https://github.com/tbarizien/defaulting-demo) to demonstrate the situation. 
The type definition I have is following : 
```go
type DefaultDemoSpec struct {
	Foo string `json:"foo,omitempty"`

	//+optional
	Car *Car `json:"car,omitempty"`
}

type Car struct {
	//+optional
	//+kubebuilder:default:=50
	Horsepower *int `json:"horsePower,omitempty"`

	//+optional
	//+kubebuilder:default:=4
	Wheels *int `json:"wheels,omitempty"`
}
```
I want to be able to get default values for my Car struct  so that applying the following yaml: 
```yaml
apiVersion: default.example.com/v1
kind: DefaultDemo
metadata:
  name: demo
  namespace: bar-iac-test
spec:
    foo: "test"
```

Would end up creating the following object:
```yaml
Spec:
  Car:
    Horse Power:  50
    Wheels:       4
  Foo:            test
```

The solution I have found is to repeat at least one of the default properties as a default object value above the `DefaultDemoSpec.Car` definition: 
```go
type DefaultDemoSpec struct {
	Foo string `json:"foo,omitempty"`

	//+optional
       //+kubebuilder:default:={wheels:4}
	Car *Car `json:"car,omitempty"`
}
```

I am not particularly satisfied with this solution as it involves duplicating the defaults. Is there a better way to do this ?
I was hoping annotating it with `default:={}` would work, but it isn't the case.

Thank you for your time
