### DISCUSSION TITLE
How to resolve an issue with double event

### DISCUSSION THREAD

**Discussion by mirisu2** [kubernetes-sigs/kubebuilder#4008] [Support] [answered]
Hi, I code 
```
func (r *ProjectReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	_ = log.FromContext(ctx)

	var project k8sv1.Project

	if err := r.Get(ctx, req.NamespacedName, &project); err != nil && errors.IsNotFound(err) {
		return ctrl.Result{}, nil
	} else if err != nil {
		log.Log.Error(err, "unable to fetch project resource")
	}

	// Namespace
	if err := r.reconcileNamespace(ctx, &project); err != nil {
		return ctrl.Result{}, err
	}
```
```
func (r *ProjectReconciler) reconcileNamespace(ctx context.Context, project *k8sv1.Project) error {
	namespace := &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name:        project.Spec.Name,
			Labels:      project.Spec.Labels,
			Annotations: project.Spec.Annotations,
		},
	}

	err := r.Get(ctx, client.ObjectKey{
		Name: project.Spec.Name,
	}, namespace)
	if err != nil && errors.IsNotFound(err) {
		if err = ctrl.SetControllerReference(project, namespace, r.Scheme); err != nil {
			return err
		}

		if err = r.Create(ctx, namespace); err != nil {
			log.Log.Error(err, fmt.Sprintf("unable to create namespace [%s]", project.Spec.Name))
			return err
		}

		log.Log.Info(fmt.Sprintf("namespace created [%s]", project.Spec.Name))

		project.Status.Namespaces = 1
		_ = r.Status().Update(ctx, project)

		return nil
	} else if err != nil {
		return err
	}

	if !reflect.DeepEqual(namespace.Labels, project.Spec.Labels) || !reflect.DeepEqual(namespace.Annotations, project.Spec.Annotations) {
		namespace.Labels = project.Spec.Labels
		namespace.Annotations = project.Spec.Annotations

		if err := r.Update(ctx, namespace); err != nil {
			log.Log.Error(err, fmt.Sprintf("unable to update namespace [%s]", project.Spec.Name))
			return err
		}

		log.Log.Info("namespace updated", "ns", project.Spec.Name)
	}

	return nil
}
```
my CustomResource
```
apiVersion: k8s.foo-tech.org/v1
kind: Project
metadata:
  name: ns1
spec:
  name: ns1
  labels:
    l1: v1
    l2: v2
  annotations:
    an1: v1
    an2: v2
```
When I apply CR, I got logs
```
2024-07-09T11:56:09+03:00       INFO    namespace created [ns1]
2024-07-09T11:56:09+03:00       INFO    namespace updated       {"ns": "ns1"}
```
namespace was successfully created.

When I add, for example, additional label and apply manifest
```
apiVersion: k8s.foo-tech.org/v1
kind: Project
metadata:
  name: ns1
spec:
  name: ns1
  labels:
    l1: v1
    l2: v2
    l3: v3
  annotations:
    an1: v1
    an2: v2
```
I got logs
```
2024-07-09T11:57:18+03:00       INFO    namespace updated       {"ns": "ns1"}
2024-07-09T11:57:18+03:00       INFO    namespace updated       {"ns": "ns1"}
```

My question is why any changes genegate double event and how I can handle this behaviour? Why this happens?
