### DISCUSSION TITLE
Why am I getting list operation denied errors for a controller created for namespace scoped resources?

### DISCUSSION THREAD

**Discussion by jwatte** [kubernetes-sigs/kubebuilder#4023] [Support] [answered]
I created a project with kubebuilder init, and added two CRDs, to be managed by namespace.
However, when installing and starting the controller, I get an error message that the controller isn't allowed to list resources at cluster scope.

Where is this disconnect (does it need to list at cluster scope? Or did I somehow manage to not restrict to namespace?), and where should I look to diagnose/update/fix this?

Versions:
Version: main.version{KubeBuilderVersion:"4.1.0", KubernetesVendor:"1.27.1", GitCommit:"de1cc60900b896b2195e403a40c976a892df4921", BuildDate:"2024-07-05T09:07:42Z", GoOs:"darwin", GoArch:"arm64"}

Here's the PROJECT file:

```
domain: example.com
layout:
- go.kubebuilder.io/v4
projectName: mps-operator
repo: github.com/example-com/mps-operator/v2
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: example.com
  kind: MPSVersion
  path: github.com/example-com/mps-operator/v2/api/v1alpha1
  version: v1alpha1
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: example.com
  kind: MPSInstance
  path: github.com/reve-ai/reve-core/backend/mps-operator/v2/api/v1alpha1
  version: v1alpha1
version: "3"
```

Errors I'm getting:

```
E0718 01:23:08.235559       1 reflector.go:150] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:106: Failed to watch *v1alpha1.MPSInstance: failed to list *v1alpha1.MPSInstance: mpsinstances.example.com is forbidden: User "system:serviceaccount:mps-operator-system:mps-operator-controller-manager" cannot list resource "mpsinstances" in API group "example.com" at the cluster scope
```

Note that I'd much rather not grant clusterrole permissions to the service account if I don't have to.
