### DISCUSSION TITLE
Nesting `resource.Quantity` inside one of the go struct adds `anyOf` validation in generated CRD

### DISCUSSION THREAD

**Discussion by abhijeet2096-confluent** [kubernetes-sigs/kubebuilder#4287] [Support]
Hey! 

I am trying to following, and I am not sure if this is a default behaviour, or if we can explicitly change via some kubebuilder markers. I am using following versions
```
❯ controller-gen --version
Version: v0.15.0

❯ kubebuilder version  
Version: main.version{KubeBuilderVersion:"4.2.0", KubernetesVendor:"1.31.0", GitCommit:"c7cde5172dc8271267dbf2899e65ef6f9d30f91e", BuildDate:"2024-08-17T09:41:45Z", GoOs:"darwin", GoArch:"arm64"}

```

I am trying to nest resource.Quantity as follows:

```
Resource    corev1.ResourceList `json:"resource,omitempty"`
```

But when I am generating CRD, this field generates 

```
                  resource:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: ResourceList is a set of (resource name, quantity)
                      pairs.
                    type: object
```

The problem I am facing is because of above `anyOf` validation, I am getting following error when I try to set cpu resource to 0.1

```
<custom crd fields above>
    resource:
      memory: 1048m
      cpu: 0.1
```

I get following error
```
* <>.resource.cpu: Invalid value: "number": <>.resource.cpu in body must be of type integer,string: "number"
* <nil>: Invalid value: "": "<>.resource.cpu" must validate at least one schema (anyOf)
* <>.resource.cpu: Invalid value: "number": <>.resource.cpu in body must be of type integer:
```

but following works as expected
```
    resource:
      memory: 1048m
      cpu: "0.1"
```

I tried the same with a  generic `Pod` yaml, and it allows me to set field to 0.1
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
  namespace: default
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: alpine/curl
    name: busybox
    resources:
      requests:
        memory: "64Mi"
        cpu: 0.1
      limits:
        memory: "128Mi"
        cpu: 500m
  dnsPolicy: ClusterFirst
  restartPolicy: Never
``` 

I am looking for guidance, on How can I instruct it to allow setting 0.1 as a valid value? I checked out kubebuilder documentation but wasn't able to find out relevant marker. 

Many Thanks!!
