### ISSUE TITLE
How to define types that unknow

### ISSUE THREAD

**Issue by chenzhiwei** [kubernetes-sigs/kubebuilder#1024]
/kind bug

Usually in a CR, the Spec structure is fixed values, such as:

```
apiVersion: example.com/v1alpha1
kind: HelloWorld
metadata:
  name: default
spec:
  replica: 3
```

But in some cases, the CR structure is unknown, such as:

```
apiVersion: example.com/v1alpha1
kind: HelloWorld
metadata:
  name: default
spec:
  config: object
```

The `object` can be:

```
key1: value1
```

or:

```
nested:
  nested:
    ...
      key1: value1
```

Can someone tell how to write the API types?
