### ISSUE TITLE
Validation for core.Volume with a SecretVolumeSource requires specifying "type: array"

### ISSUE THREAD

**Issue by trisberg** [kubernetes-sigs/kubebuilder#1128]
I've created a CRD that has a spec field defines as:

```
	// Template volume
	Template *corev1.Volume `json:"template,omitempty"`
```

This generates validation for the CRD and when I try to create an instance of the CRD I get validation error if I don't provide a `type: array` as part of the SecretVolumeSource for the Volume definition.

```
apiVersion: test.example.com/v1alpha1
kind: Example
metadata:
  name: mytest
spec:
  template:
    name: myvolume
    secret:
      type: array
      secretName: test-secret
      items:
      - key: pasword
        path: password
```

If I leave out `type: array` I get this validation error:

```
$ k apply -f -
apiVersion: test.example.com/v1alpha1
kind: Example
metadata:
  name: mytest
spec:
  template:
    name: myvolume
    secret:
      secretName: test-secret
      items:
      - key: pasword
        path: password
The Example "mytest" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"test.example.com/v1alpha1", "kind":"Example", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"test.example.com/v1alpha1\",\"kind\":\"Example\",\"metadata\":{\"annotations\":{},\"name\":\"mytest\",\"namespace\":\"default\"},\"spec\":{\"template\":{\"name\":\"myvolume\",\"secret\":{\"items\":[{\"key\":\"pasword\",\"path\":\"password\"}],\"secretName\":\"test-secret\"}}}}\n"}, "creationTimestamp":"2019-10-25T15:59:27Z", "generation":1, "name":"mytest", "namespace":"default", "uid":"6c054e4d-f740-11e9-9d56-42010a8000cc"}, "spec":map[string]interface {}{"template":map[string]interface {}{"name":"myvolume", "secret":map[string]interface {}{"items":[]interface {}{map[string]interface {}{"key":"pasword", "path":"password"}}, "secretName":"test-secret"}}}}: validation failure list:
type in spec.template.secret is required
```

I've never had to provide this `type: array` definition when using a SecretVolumeSource for a Deployment or Pod before.

Any thoughts on this? My code is in https://github.com/trisberg/test
