### ISSUE TITLE
Feature Request: support "empty" group for API resources, i.e. with group == domain

### ISSUE THREAD

**Issue by hypnoglow** [kubernetes-sigs/kubebuilder#1404]
I would like to see kubebuilder support creating APIs with empty groups. By that I mean that the actual `apiVersion` of CRD to be `domain/version` without additional group prefix.

I think this can be very helpful for controllers/operators with a very narrow scope and a small number of `Kind`-s fitting into single "root" group.

Consider popular examples, such as [cert-manager](https://github.com/jetstack/cert-manager) or [jaeger-operator](https://github.com/jaegertracing/jaeger-operator):

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-com
```

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
```

In this examples there is no "groups" in terms of kubebuilder, and one group in terms of Kubernetes resource (for kubebuilder it is`group == domain`). And for many such cases it would be desirable to design APIs in a similar simple way.

/kind feature
