### ISSUE TITLE
Bind log configuration flags by default in main.go

### ISSUE THREAD

**Issue by bharathi-tenneti** [kubernetes-sigs/kubebuilder#1517]
Description: 
Update the `main.go` scaffold code to configure log options from command line flags via [`zap.BindFlags()`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/log/zap/zap.go#L219)
Example:
```Go
opts := zap.Options{}
opts.BindFlags(flag.CommandLine)
flag.Parse()
logger := zap.New(zap.UseFlagOptions(&opts))
log.SetLogger(logger)
```
This way, the log options can be configured at runtime via flags in the manager’s deployment manifest e.g:
```YAML
  spec:
    containers:
    - command:
      - /manager
      args:
      - --enable-leader-election
      - --zap-devel=true
      - --zap-log-level=debug
```
/kind feature
