### ISSUE TITLE
Incorrect CRD generated after adding webhook/ca injection patches to kustomize

### ISSUE THREAD

**Issue by robherley** [kubernetes-sigs/kubebuilder#1633]
When adding the patches for webhooks/cert manager, the subresources field for the CRD is empty and missing the status field.

**Steps to reproduce:**
```
$ kubebuilder init --domain robherley.xyz --repo github.com/robherley/example 
$ kubebuilder create api --group=example --version=v1alpha1 --kind=Foobar

<added subresource marker to _types file>

$ make manifests

$ kustomize build config/default | grep subresources -C 1
  scope: Namespaced
  subresources:
    status: {}

<uncommented the patches in config/crd/kustomization.yaml>

$ kustomize build config/default | grep subresources -A 1
  scope: Namespaced
  subresources: {}
  validation:
```

* go version
v1.14.5
* kubebuilder version (`kubebuilder version`) and scaffolding version (check your `PROJECT` file)
kubebuilder: v2.3.1 and scaffolding: v2
* controller-runtime version (check your `go.mod` file)
v0.5.0
* Kubernetes & kubectl versions (just run `kubectl version` against your API server)
client: v1.18.3 and server: v1.17.1

/kind bug

**Comment by camilamacedo86** [comment]
Hi @robherley, 

Could you please check it with the master branch and the v3-alpha plugin? 

E.g: 
>    kubebuilder init --plugins=go/v3-alpha --domain=tutorial.kubebuilder.io --project-version=3-alpha --repo=tutorial.kubebuilder.io/project --license apache2 --owner "The Kubernetes authors"

Let's see it is not solved with the latest version and plugin. Also, if not could you please clarify what is the value scaffolded as you did and what is the value expected by you?

**Comment by robherley** [comment]
Here's the steps I followed for the master branch (3c4eb4f9):

```
$ kubebuilder init --plugins=go/v3-alpha --domain=tutorial.kubebuilder.io --project-version=3-alpha --repo=tutorial.kubebuilder.io/project --license apache2 --owner "The Kubernetes authors"

$ kubebuilder create api --group=example --version=v1alpha1 --kind=Foobar

$ make manifests

$ kustomize build config/default > before_patch.yaml
```

That yaml has the correct spec.subresources.status for the CustomResourceDefinition:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: foobars.example.tutorial.kubebuilder.io
spec:
  group: example.tutorial.kubebuilder.io
  names:
    kind: Foobar
    listKind: FoobarList
    plural: foobars
    singular: foobar
  scope: Namespaced
  subresources:
    status: {} # this is correct
  validation:
...
```

But if I uncomment the patches for the webhooks in `config/crd/kustomization`:
```yaml
patchesStrategicMerge:
  - patches/webhook_in_foobars.yaml
  - patches/cainjection_in_foobars.yaml
```

And regenerate the manifests:
```
$ make manifests

$ kustomize build config/default > after_patch.yaml
```

It's missing the status subresource:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
    controller-gen.kubebuilder.io/version: v0.2.5
  name: foobars.example.tutorial.kubebuilder.io
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      caBundle: Cg==
      service:
        name: webhook-service
        namespace: foobar2-system
        path: /convert
  group: example.tutorial.kubebuilder.io
  names:
    kind: Foobar
    listKind: FoobarList
    plural: foobars
    singular: foobar
  scope: Namespaced
  subresources: {} # missing status
  validation:
...
```

I've attached `before_patch.yaml` and `after_patch.yaml`: [generated.zip](https://github.com/kubernetes-sigs/kubebuilder/files/5080944/generated.zip)
