### ISSUE TITLE
Deploying manager pod as non-root

### ISSUE THREAD

**Issue by harpratap** [kubernetes-sigs/kubebuilder#1637]
I tried deploying the manager on our K8s platform that doesn't allow root by default but ran into following issues even though there's nothing really in the manager that requires root
I see the following two errors -
1. `Error: container has runAsNonRoot and image will run as root` 
2. `Error: container has runAsNonRoot and image has non-numeric user (nonroot), cannot verify user is non-root`

We use the following podsecuritypolicy to ensure that pods are not running as root -
```
allowPrivilegeEscalation: true
  allowedCapabilities:
  - NET_RAW
  - NET_BIND_SERVICE
  fsGroup:
    rule: RunAsAny
  requiredDropCapabilities:
  - CHOWN
  - DAC_OVERRIDE
  - SETPCAP
  - MKNOD
  - AUDIT_WRITE
  - FOWNER
  - FSETID
  - KILL
  - SETGID
  - SETUID
  - SYS_CHROOT
  - SETFCAP
  - SYS_MODULE
  - SYS_RAWIO
  - SYS_PACCT
  - SYS_ADMIN
  - SYS_NICE
  - SYS_RESOURCE
  - SYS_TIME
  - SYS_TTY_CONFIG
  - AUDIT_CONTROL
  - MAC_OVERRIDE
  - MAC_ADMIN
  - NET_ADMIN
  - SYSLOG
  - DAC_READ_SEARCH
  - LINUX_IMMUTABLE
  - NET_BROADCAST
  - IPC_LOCK
  - IPC_OWNER
  - SYS_PTRACE
  - SYS_BOOT
  - LEASE
  - WAKE_ALARM
  - BLOCK_SUSPEND
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
```

I believe this is happening because of two reasons -
1. The kube-rbac-proxy uses root by default, since it is using distroless/static as it's base image - https://github.com/brancz/kube-rbac-proxy/blob/master/Dockerfile#L1 I got this from this comment - https://github.com/GoogleContainerTools/distroless/issues/235#issuecomment-422099277

2. The manager image is using nonroot:nonroot user - https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/v2/scaffolds/internal/templates/dockerfile.go#L65 

I have made some changes in #1635 which made it work in our cluster with the nonroot accounts.

What versions of software are you using?  Specifically, the following are often useful:

* go version - 1.13
* kubebuilder version (`kubebuilder version`) and scaffolding version (check your `PROJECT` file) 2.3.1 and v2
* controller-runtime version (check your `go.mod` file) v0.6.0
* Kubernetes & kubectl versions (just run `kubectl version` against your API server) v1.18.6

/kind bug
