### ISSUE TITLE
Document kustomize version to be used with Kubebuilder 

### ISSUE THREAD

**Issue by rajasaur** [kubernetes-sigs/kubebuilder#1655]
The CRDs generated by kustomize for Status Subresource handling seems to be dropped off in Kustomize 3.8.0 and beyond. After adding the `// +kubebuilder:subresource:status` marker which generates the 
``` 
subresources:
    status: {}
```
section in the config/crd/bases folder, running a `kustomize build config/crd` doesnt seem to update the final CRD with the status subresource. This causes any updates on the Status resource to fail with a. 404 because the Status object never got created in the first place.

This is the output of Kustomize 3.8.0 before.
```
emerald:d5doperator raja$ ./kustomize build config/crd | more  
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
    controller-gen.kubebuilder.io/version: v0.3.0
  name: pipelines.operations.starsystems.in
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      caBundle: Cg==
      service:
        name: webhook-service
        namespace: system
        path: /convert
  group: operations.starsystems.in
  names:
    kind: Pipeline
    listKind: PipelineList
    plural: pipelines
    singular: pipeline
  preserveUnknownFields: false
  scope: Namespaced
  subresources: {}
``` 

This is the output from Kustomize 3.7.0 :
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: pipelines.operations.starsystems.in
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      caBundle: Cg==
      service:
        name: webhook-service
        namespace: system
        path: /convert
  group: operations.starsystems.in
  names:
    kind: Pipeline
    listKind: PipelineList
    plural: pipelines
    singular: pipeline
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
```

Pls notice the output of the subresources in both the cases.

Release Notes from Kustomize 3.8.0: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.8.0

* Go version: 1.13.15
* Kubebuilder: 2.3.1
* Controller-runtime: v0.4.0

/kind documentation
/kind bug

It might help to just update the kustomize version to avoid people having this issue.
