### ISSUE TITLE
Webhook configuration to allow namespaceSelector

### ISSUE THREAD

**Issue by YiannisGkoufas** [kubernetes-sigs/kubebuilder#1672]
On the documentation about Webhook's on core types (like pods) https://book.kubebuilder.io/cronjob-tutorial/running-webhook.html t is mentioned that we should use namespaceSelector.

However if I am not wrong it's not part of the API according to this  https://book.kubebuilder.io/reference/markers/webhook.html

I am aware that we can always add it on the yaml afterwards but still it would be nice to have it in the markers as well

/kind feature

**Comment by camilamacedo86** [comment]
hi @YiannisGkoufas, 

Sorry for the delay. It is open for a while. Could you please let us know if that still relevant?  If yes, could you please, provide an example of the scenario with code snippets to clarify that?

**Comment by akirillov** [comment]
@YiannisGkoufas, one of the alternative solutions would be providing a strategic merge patch containing the namespace selector. That way, all the manifests generated by the kubebuilder tooling (`make manifests`) will not override the changes upon the consequent runs.

Example:
`webhook/namespace_selector_patch.yaml`
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: your.webhook.name
  namespaceSelector:
    matchExpressions:
    - key: label
      operator: In
      values: ["true"]
```
where `your.webhook.name` comes from `manifests.yaml` where it is in turn generated from `+kubebuilder:webhook:name=your.webhook.name`. And then the path to the patch should be added to `webhook/kustomization.yaml`
```
patchesStrategicMerge:
- namespace_selector_patch.yaml
```
