### ISSUE TITLE
Add the controller-gen markers in types.go if the --plural is specified

### ISSUE THREAD

**Issue by prafull01** [kubernetes-sigs/kubebuilder#1805]
This is a follow up of the following PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1802

Controller-gen markers for apis should be added if the specific plural is provided by the user. Lets consider the following scenario:
```
prafull@EMPID18004:~/go/src/github.com/prafull01/kubebuilder/proj$ ../bin/kubebuilder create api --group=praf --kind=Fernandez --version=v1 --plural=Fernandezes
Create Resource [y/n]
y
Create Controller [y/n]
y
Writing scaffold for you to edit...
api/v1/fernandez_types.go
controllers/fernandez_controller.go
Running make:
$ make
/home/prafull/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
go build -o bin/manager main.go
```

PROJECT file:
```
prafull@EMPID18004:~/go/src/github.com/prafull01/kubebuilder/proj$ cat PROJECT 
domain: my.domain
layout: go.kubebuilder.io/v3-alpha
projectName: proj
repo: sigs.k8s.io/kubebuilder/v2
resources:
- group: praf
  kind: Fernandez
  plural: Fernandezes
  version: v1
version: 3-alpha
```
CRD file:
```
group: praf.my.domain
  names:
    kind: Fernandez
    listKind: FernandezList
    plural: fernandezs
    singular: fernandez
  scope: Namespaced
```

It should add marker ([here](https://github.com/kubernetes-sigs/controller-tools/blob/6fa696de4772fb44595d25355946254885a202df/pkg/crd/markers/crd.go#L246)) in the api/_types.go file which will actually add the plurals in the CRD as well.

/kind bug
