### ISSUE TITLE
Project file with all user input data

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1826]
**Description**

Ensure that we are storing all input data in the PROJECT file. 

**Motivation**
I am maintainer like to ensure that we have stored all input data used to scaffold the projects by the user so that I could propose a subcommand/plugin to help users migrate from a plugin version X to X+1 since would be possible scaffold the project from the scratch. Also, it might be helpful in many scenarios to tooling the scaffolds. 

Mor info: See: https://github.com/kubernetes-sigs/kubebuilder/pull/1644#discussion_r491227667

**What is missing to be stored**

- [ ] Webhooks data
- [ ] resource/controller=[true|false]  

/kind feature

**Comment by camilamacedo86** [comment]
PR related : https://github.com/kubernetes-sigs/kubebuilder/pull/1696

**Comment by camilamacedo86** [comment]
Hi @estroz, @joelanford, @DirectXMan12, @pwittrock  I am pushing it for v3+plugin for we have the chance to discuss it and try to achieve it for the release if we agree on that.

**Comment by estroz** [comment]
>hasResource and hasController for the resources

Maybe only hasResource? If you're building a type library you would set `--controller=false --resource=true`, so we'd probably want to set `hasResource: true` or `types: true` field for its GVK. Conversely, one major reason you would have `--resource=false --controller=<true|false>` set is if you're using an external type; the config can store an external type path as something like `external: <import path>` (see #1772) instead of `controller: true`.

>from the init owner and license

These are already captured in `hack/boilerplate.go.txt` so these don't need to be tracked in the config.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

> These are already captured in hack/boilerplate.go.txt so these don't need to be tracked in the config. 👍 

Totally agree. Good point. 

> Maybe only hasResource?

Since we can resource = false and controller=true as resource = true and controller=false, IMO this one we need to track.

**Comment by estroz** [comment]
Prior to releasing v3.0.0, the config spec for version `3-alpha` needs to be stabilized. A few changes have been added to or are proposed for `3-alpha`. To summarize:
- Added `resources[].crdVersion` and `resources[].webhookVersion` when `--crd-version` and `--webhook-version` are set, respectively (#1644)
- Add `resources[].api` and `resources[].controller` when `--resource` and `--controller` are set, respectively (#1849)
- Add `resources[].webhooks` for defaulting, validating, and conversion webhooks (#1696)

These additions are being made (not intentionally) without considering what they'll look like together, but should be. Perhaps a redesign of `resources` is in order instead of tacking on new fields to the version 2 implementation. Something like the following:

```yaml
version: 3-alpha
resources:
- api: # api contains all important information from `create api`
    group: my.domain
    version: v1
    kind: CronJob
    crdVersion: v1
    controller: true
  webhook: # webhook contains all important information from `create webhook`
    webhookConfigVersion: v1
    types:
    - validating
    - mutating
    - conversion
```

The above design groups fields by `create` subcommand, which is logical given the expected `kubebuilder` command flow of `init -> create api -> create webhook`.

@Adirio @DirectXMan12 @pwittrock thoughts on making this decision

**Comment by Adirio** [comment]
My thoughts but written by you. 100% agree. And 100% in favor of omiting as many of these fields as possible if they are default values.

**Comment by joelanford** [comment]
Each plugin can define its own flags, so would the plugin also control these fields?

**Comment by estroz** [comment]
>Each plugin can define its own flags, so would the plugin also control these fields?

Yes. These fields are intended to be general enough such that any plugin can make use of them. If they aren't used by a plugin, then they're omitted from the config, so the user will never have to worry about them.

>Either way, I feel like this is a pretty major change right as we're trying to stabilize v3

I am worried about that. Perhaps we should punt on this issue, #1696, and #1849 for now and go with what exists in the current spec, since none of the fields mentioned in this issue or those PRs are necessary for v3.0.0 features.

**Comment by Adirio** [comment]
What do you think about the following model:
![kubebuilder-model](https://user-images.githubusercontent.com/522770/100076702-c94dc080-2e41-11eb-97f6-ea27f2ebd6ac.png)

```
version: 3-alpha
domain: my-domain.com
crdVersion: v1beta1
webhookVersion: v1beta1
apis:
  - resource:
      group: Ships
      # version omitted meand v1
      kind: Boat
      # plural omitted means Boats
      # domain omitted means my-domain.com (see line 2)
      # package omitted means it is not an external type
    definition:
      # version omitted means v1beta1 (see line 3)
      namespaced: true
    controller: true
    webhooks:
      # version omitted means v1beta1 (see line 4)
      types:
        - validating
  - resource:
      group: Animals
      version: v2
      kind: Sheep
      plural: Flock
      domain: my-animals.com
      package: "github.com/owner/repo/apis/animals"
      controller: true
```

**Comment by camilamacedo86** [comment]
Hi @Adirio and @estroz,  

Thank you for your contribution. 

I do NOT agree with them because controllers are NOT APIs and what is suggested here is out of the scope of this issue. Also, see that the proposals here are ONLY to start to track the missing info and NOT change the PROJECT file design at all. 

I totally agree with @joelanford that we should NOT redesign the PROJECT file for v3. However, folks feel free to raise new issues with your ideas with its purpose to be addressed for v4 plugin. Why we should get merged the  (Webhooks data: PR: #1696 and resource/controller=[true|false] #1849) as it is shaped so far for v3? 

- It will allow us to provide a tool to migrate in the future project from v3 for v4 plugin whcih will address a common request made by the community. Users have been reporting that they find hard this process indeed in the SDK survey
- It will allow us to improve the tooling features for the plugins. 
- It will increase the maintainability
- The PRs are not changing the current design. The PRs are only adding the respective fields as we have been discussing for a while. Then, if we decide to change its design in the v4 as you are suggesting we can tooling the migration and make this process easier for the users.

**Comment by camilamacedo86** [comment]
Hi @Adirio and @estroz,

**Currently, we have the following model:** 

```yaml
domain: testproject.org
layout: go.kubebuilder.io/v3-alpha
multigroup: true
projectName: project-v3-multigroup
repo: sigs.k8s.io/kubebuilder/testdata/project-v3-multigroup
resources:
- crdVersion: v1
  group: crew
  kind: Captain
  version: v1
  webhookVersion: v1
````

**After we merge the PRs  #1696 and  #1849 we will have the model:**

```yaml
domain: testproject.org
layout: go.kubebuilder.io/v3-alpha
multigroup: true
projectName: project-v3-multigroup
repo: sigs.k8s.io/kubebuilder/testdata/project-v3-multigroup
resources:
- crdVersion: v1
  group: crew
  kind: Captain
  version: v1
  webhookVersion: v1
  apis:true // is true when a GKV has an API scaffolded
  controller:false   // is true when a GKV has an controller scaffolded
  webhooks: // respresents the webhooks
    defaulting: true
    validation: true
```

**why I do not agree with the suggestions made?**

It shows hurts concepts such as DDD and adds limitations which mean possible breaking changes in the future as described in https://github.com/kubernetes-sigs/kubebuilder/issues/1772#issuecomment-736717387 since it is not authentic to the representations of the resources. 

**So, besides I still believing that re-design the PROJECT file is out of the scope of this issue, WDYT tries to list here what are the problems faced with the current model and then, we see if we can find a model/solution more appropriated to address them? Could you please add the use cases that would be solved with the suggestions made or that you see that cannot be addressed with the current model to clarify your motivations?**

c/c @DirectXMan12  @pwittrock @gabbifish  WDYT?

**Comment by Adirio** [comment]
`resources[].webhooks.webhookConfigVersion` is too verbose, `resources[].webhooks.version` should be more than enough.

I wouldn't use subcommand names either. Subcommands are based on the most common workflows followed by projects. The most commong thing is to scaffold both the resource type and its controller and that is why they are grouped. Webhooks are less common so they are provided as a separate subcommand. However I do think we need to group and structure this field better.

Previously, the project file just stored GVK (Group-Version-Kind). Having two object that represent a resource for the config file (`pkg/model/config.GVK`) and for internal use (`pkg/model/resource.Resource`) wasn't that much of an issue mainly because `pkg/model/config.GVK` was pretty small and its a k/k concept. However we have been adding fields and more fields to this `pkg/model/config.GVK` to the point where it has transitioned into `pkg/model/config.ResourceData`. Which is the problem with this? we have two different types that represent the same concept for the project configuration file and internal usage. This is proof of a poor design, and will arise a lot of problems in the future, for example when working with out-of-tree plugins. So, I strongly think that we should have a single `Resource` model that is able to store all this information and save it to the config file as needed.

I think that another issue here is that each of us is calling API to a different thing. You are calling API to whatever gets scaffolded when you do `kubebuilder create api --resource --controller=false ...` which in reality is just the golang type definition and the CRD, and that is the reason why I used the term `Definition` in my model to refer to it. The controller, from a kubebuilder viewpoint, is also part of the API as you create it with `kubebuilder create api --controller ...`. Webhooks, however, are not created by `kubebuilder create api` despite being scaffolded in the `api[s]` directory. Probably this is due to the fact that webhhoks are not required as often as the controller and because in v1 webhooks weren't supported from the start and they were added as a `kubebuilder alpha` subcommand. The point here is that API is missleading and that's the reason why I would not use it. I suggest using `Definition`, `Controller` and `Webhooks` to refer to the three parts that we are scaffolding. I think that stop using the term API will make things clear (I'm not suggesting to remove the command name `api`, at least for backwards compatibility reasons)

**Comment by camilamacedo86** [comment]
Hi @estroz and @Adirio,

To make it easier I centralized all changes in the same PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1696/files. Also, I addressed all suggestions that shows that we 3 can reach a consensus and does NOT mean a breaking change:

```yaml
componentConfig: true
domain: testproject.org
layout: go.kubebuilder.io/v3-alpha
projectName: project-v3-config
repo: sigs.k8s.io/kubebuilder/testdata/project-v3-config
resources:
- api: true
  controller: true
  crdVersion: v1
  group: crew
  kind: Captain
  version: v1
  namespaced: true
  webhooks:
    apiVersion: v1
    defaulting: true
    validation: true
```

**Why not add the api as structure as suggested by @estroz which is +1 for me as well?**

Its result ith the suggestion would be: 

```yaml
componentConfig: true
domain: testproject.org
layout: go.kubebuilder.io/v3-alpha
projectName: project-v3-config
repo: sigs.k8s.io/kubebuilder/testdata/project-v3-config
resources:
- api:
    namespaced: true
    apiVersion:v1
  controller: true
  group: crew
  kind: Captain
  version: v1
  webhooks:
    apiVersion: v1
    defaulting: true
    validation: true
```

I also agree with @estroz that would be great. However, it means a breaking change and then, I still think that we should push it to v4.
