### ISSUE TITLE
use a NetworkPolicy instead of kube-rbac-proxy

### ISSUE THREAD

**Issue by estroz** [kubernetes-sigs/kubebuilder#1885]
[kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy/), while a nice feature, is a third-party workaround for a problem (restricting pod access to `/metrics`) that can be solved by a [`NetworkPolicy`](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource). For example, the following policy could be scaffolded by default so only manager-related pods could be selected:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy
  namespace: system
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          control-plane: controller-manager
    - podSelector:
        matchLabels:
          control-plane: controller-manager
```

Benefits:
1. k8s-native resource.
1. Reduces the number of external dependencies.
1. Easy to use and modify.

/kind feature
