### ISSUE TITLE
Wrong path for probes

### ISSUE THREAD

**Issue by zoetrope** [kubernetes-sigs/kubebuilder#1904]
When I generated the codes with kubebuilder v3-alpha.0, I got the following manifest:

```yaml
        livenessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
```

Is this correct?
I believe `readinessProbe` should use `readyz`.

/kind bug
