### ISSUE TITLE
(Bug) Can not convert go primitive type to JSON schema type

### ISSUE THREAD

**Issue by fanzhangio** [kubernetes-sigs/kubebuilder#200]
#parsePrimitiveValidation()# is responsible for converting go primitive type to JSON schema type: like `int, int64, uint64 -> integer`, `bool -> boolean`

But the generated CRD yaml file does not apply these conversion.

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: ""
    kubebuilder.k8s.io: unknown
  name: houses.got.sample.kubernetes.io
spec:
  group: got.sample.kubernetes.io
  names:
    kind: House
    plural: houses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            alias:
              enum:
              - Lion
              - Wolf
              - Dragon
              type: string
            knights:
              items:
                maxItems: 500
                minItems: 1
                type: string
              maxItems: 500
              minItems: 1
              type: array
            name:
              maxLength: 15
              minLength: 1
              type: string
            power:
              exclusiveMinimum: true
              maximum: 100
              type: int         # Should be integer
            rank:
              enum:
              - 1
              - 2
              - 3
              type: int
            winner:
              type: bool      # Should be boolean
          type: object
        status:
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
```
