### ISSUE TITLE
Info has not been tracked when the resource is not generated

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2001]
By running `kubebuilder create api --group core --version v1 --kind Pod --resource=false --controller=true`;

```
$ kubebuilder create api --group core --version v1 --kind Pod --force
Create Resource [y/n]
n
Create Controller [y/n]
y
Writing scaffold for you to edit...
controllers/pod_controller.go
Running make:
$ make generate
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.4.1
/Users/camilamacedo/go/src/example/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
```

So, the above scenario results now in:

```ymal
 $ cat PROJECT 
domain: my.domain
layout: go.kubebuilder.io/v3
projectName: example
repo: example
version: "3"
```

When should be 

```
domain: my.domain
layout: go.kubebuilder.io/v3
projectName: example
repo: example
resources:
- controller: true
  group: core
  kind: Pod
  path: k8s.io/core/apps/v1 // we might want to leave empty this one until we implement an RFE to support external types.
  version: v1
version: "3"
```
