### ISSUE TITLE
Add support for required field in parsing CRD validation

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kubebuilder#207]
For following struct, `Enabled` should be in the `Required` list.
```
type IAP struct {
	Enabled           bool                    `json:"enabled"`
	ClientCredentials *OAuthClientCredentials `json:"clientCredentials,omitempty"`
}
```
However, currently we are missing that part in generated card
```
            iap:
              properties:
                clientCredentials:
                  properties:
                    secret:
                      type: string
                  type: object
                enabled:
                  type: bool
              type: object
```
The correct one should be
```
            iap:
              properties:
                clientCredentials:
                  properties:
                    secret:
                      type: string
                  required:
                  - secret
                  type: object
                enabled:
                  type: bool
              required:
              - enabled
              type: object
```
