### ISSUE TITLE
conversion webhook scaffolding for multi-group api

### ISSUE THREAD

**Issue by michelleN** [kubernetes-sigs/kubebuilder#2140]
```
$ kubebuilder create webhook --group <group> --version <version>  --kind <Kind> --conversion

2021/04/12 10:46:19 failed to create webhook: unable to inject the resource to "base.go.kubebuilder.io/v3": kubebuilder create webhook requires a previously created API
```

I expected the conversion webhook file to be scaffolded.

I think what might be happening is that the command is not finding the resource potentially because it is under the `apis/` directory? 

/kind bug

**Comment by camilamacedo86** [comment]
You cannot create a webhook if you do not have an API for that. 
Did you create an API for that?

**Comment by michelleN** [comment]
Yes I do. It is under `apis/<group>/<version>` from my root directory

**Comment by Adirio** [comment]
Can you post your `PROJECT` file (you can skip fields if you want but im interested in `version` and the corresponding element in the `resources` list.

**Comment by camilamacedo86** [comment]
Hi @michelleN, 

The tool store what is scaffold in the PROJECT file. If you do things manually without the tool then, is not possible to ensure that it will still be working as should be. As a workaround, you can try to fix that by updating the Project file or just re-scaffolding the api with the tool and adding your code back.

**Comment by camilamacedo86** [comment]
Hi @michelleN, 

You can check [here](https://master.book.kubebuilder.io/reference/project-config.html) the documentation over the project config. Also, you can check further information about the project file and its changes in the [migration guide from v2 to v3](https://master.book.kubebuilder.io/migration/v2vsv3.html). See [here](https://master.book.kubebuilder.io/migration/manually_migration_guide_v2_v3.html#migration-from-project-config-version-2-to-3).

Since it seems not a bug in the CLI itself I am closing this one. However, please feel free to contact us if you think that it should be re-opened.

**Comment by alekc** [comment]
Encountered this issue as well, so giving a bit more context in here (might help to anyone hitting this)

My PROJECT file is following:
```yaml
domain: k8s.alekc.dev
layout:
- go.kubebuilder.io/v3
projectName: gitlab-runner-operator
repo: gitlab.k8s.alekc.dev
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: k8s.alekc.dev
  group: gitlab
  kind: Runner
  path: gitlab.k8s.alekc.dev/api/v1beta1
  version: v1beta1
  webhooks:
    defaulting: true
    validation: true
    webhookVersion: v1
version: "3"
```

and I was using following command:
`❯ kubebuilder create webhook --group gitlab --version v1beta1 --kind Runner --defaulting --programmatic-validation`

the error message comes from this block:
```go
if r, err := p.config.GetResource(p.resource.GVK); err != nil {
		return fmt.Errorf("%s create webhook requires a previously created API ", p.commandName)
	}
```
where `GetResource` is simply checking that  one of your entries from `resources` key has the same `Group` `Version` and `Kind`

```go
func (c cfg) GetResource(gvk resource.GVK) (resource.Resource, error) {
	for _, res := range c.Resources {
		if gvk.IsEqualTo(res.GVK) {
			r := res.Copy()

			// Plural is only stored if irregular, so if it is empty recover the regular form
			if r.Plural == "" {
				r.Plural = resource.RegularPlural(r.Kind)
			}

			return r, nil
		}
	}

	return resource.Resource{}, config.ResourceNotFoundError{GVK: gvk}
}
...
func (gvk GVK) IsEqualTo(other GVK) bool {
	return gvk.Group == other.Group &&
		gvk.Domain == other.Domain &&
		gvk.Version == other.Version &&
		gvk.Kind == other.Kind
}
```

In my case I was using a v1 in the command, and in my config it was v1beta1

Ideally, the error message should be a bit less vague and report something like along the lines `could not fine resource x/y/z, has resources x/y/zzz, a/b/c`. Just 2 cents
