### ISSUE TITLE
kubebuilder Failed to create CronJob V2 conversion webhook: webhook resource already exists

### ISSUE THREAD

**Issue by ka-keung** [kubernetes-sigs/kubebuilder#2554]
### What broke? What's expected?

!!! same as https://github.com/kubernetes-sigs/controller-tools/issues/659#issue-1173359586 move to here !!!

i had followed the book [kubebuilder](https://kubebuilder.io/) step by step deploy the v1 cronjob crd and webhook. it was successful.

but the follow chapter  [Multi-Version API](https://kubebuilder.io/multiversion-tutorial/tutorial.html#tutorial-multi-version-api) . the problem was exist. that was my step

## step 1: 
follow book, finish deploy this chapter content
[Tutorial: Building CronJob](https://kubebuilder.io/cronjob-tutorial/cronjob-tutorial.html#tutorial-building-cronjob)

## step 2:
retain prev chapter set up on k8s,move to this chapter
[Tutorial: Multi-Version API](https://kubebuilder.io/multiversion-tutorial/tutorial.html#tutorial-multi-version-api) 

```
kubebuilder create api --group batch --version v2 --kind CronJob
Create Resource [y/n]
y
Create Controller [y/n]
n
```

step 2: same as book. but until webbook section [Setting up the webhooks](https://kubebuilder.io/multiversion-tutorial/webhooks.html#setting-up-the-webhooks)
```
kubebuilder create webhook --group batch --version v2 --kind CronJob --conversion
Error: failed to create webhook: unable to inject the resource to "base.go.kubebuilder.io/v3": webhook resource already exists
```

and i had stick here for long time . and i had looked back this section many times . but i can't found any step i was missed or wrong, that's  why ????

here is my PROJECT file:

```
domain: tutorial.kubebuilder.io
layout:
- go.kubebuilder.io/v3
projectName: kubebuilder
repo: tutorial.kubebuilder.io
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: tutorial.kubebuilder.io
  group: batch
  kind: CronJob
  path: tutorial.kubebuilder.io/api/v1
  version: v1
  webhooks:
    defaulting: true
    validation: true
    webhookVersion: v1
- api:
    crdVersion: v1
    namespaced: true
  domain: tutorial.kubebuilder.io
  group: batch
  kind: CronJob
  path: tutorial.kubebuilder.io/api/v2
  version: v2
version: "3"
```

### KubeBuilder (CLI) Version

3.3.0

### PROJECT version

3

### Other versions

go: 1.18  or 1.16 (both i had try)
k8s: v1.21.9
