### ISSUE TITLE
metadata field not created after creation of resource

### ISSUE THREAD

**Issue by akgowda** [kubernetes-sigs/kubebuilder#2727]
### Discussed in https://github.com/kubernetes-sigs/kubebuilder/discussions/2726

<div type='discussions-op-text'>

<sup>Originally posted by **akgowda** June 14, 2022</sup>
I created a Deployment wrapper Controller. But the template's metadata field is empty even though I've added labels/annotations to the resource.
```
apiVersion: test.domain/v1
kind: DhruvaDeployment
metadata:
  name: dhruvadeployment-sample
spec:
  deploymentSpec:
    selector:
      matchLabels:
        foo: bar
    template:
      metadata:
        labels:
          foo: bar
        annotations:
          test1: testAnnot
      spec:
        containers:
          - name: app
            image: busybox
            args:
              - /bin/sh
              - -c
              - "date; echo Hello from the Kubernetes cluster; trap : TERM INT; sleep infinity & wait"


```

------
```
ubuntu@master-node:~$ kubectl  get dhruvadeployments.test.domain dhruvadeployment-sample -o yaml
apiVersion:test.domain/v1
kind: DhruvaDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"test.domain/v1","kind":"DhruvaDeployment","metadata":{"annotations":{},"name":"dhruvadeployment-sample","namespace":"default"},"spec":{"deploymentSpec":{"selector":{"matchLabels":{"foo":"bar"}},"template":{"metadata":{"annotations":{"test1":"testAnnot"},"labels":{"foo":"bar"}},"spec":{"containers":[{"args":["/bin/sh","-c","date; echo Hello from the Kubernetes cluster; trap : TERM INT; sleep infinity \u0026 wait"],"image":"busybox","name":"app"}]}}}}}
  creationTimestamp: "2022-06-14T10:37:34Z"
  generation: 2
  name: dhruvadeployment-sample
  namespace: default
  resourceVersion: "2426014"
  uid: 711a4a99-6537-4a18-9977-bc7d925dfa15
spec:
  deploymentSpec:
    selector:
      matchLabels:
        foo: bar
    template:
      metadata: {}
      spec:
        containers:
        - args:
          - /bin/sh
          - -c
          - 'date; echo Hello from the Kubernetes cluster; trap : TERM INT; sleep
            infinity & wait'
          image: busybox
          name: app
</div>
