### ISSUE TITLE
Is there any way to validation string array items in enum

### ISSUE THREAD

**Issue by moxianfeng** [kubernetes-sigs/kubebuilder#2812]
### Discussed in https://github.com/kubernetes-sigs/kubebuilder/discussions/2811

<div type='discussions-op-text'>

<sup>Originally posted by **moxianfeng** July  8, 2022</sup>
if I have a struct like

```
type AA struct {
    // +kubebuilder:validation:MinItems=1
    // +kubebuilder:validation:Enum=admin;reseller;operator
    Role []string `json:"role,omtiempty"
}
```

and make manifests， will get below result

```
           properties:
              role:
                enum:
                - admin
                - reseller
                - tenantAdmin
                - tenantOperator
                - tenantDeveloper
                - tenantService
                items:
                  type: string
                minItems: 1
                type: array
```

The desired output is

```
           properties:
              role:
                items:
                  enum:
                  - admin
                  - reseller
                  - tenantAdmin
                  - tenantOperator
                  - tenantDeveloper
                  - tenantService
                  type: string
                minItems: 1
                type: array
```

but I don't know how to mark the field.
</div>
