### ISSUE TITLE
Escape hatch for CRD validation

### ISSUE THREAD

**Issue by ecordell** [kubernetes-sigs/kubebuilder#301]
It would be nice to have to a way to specify an arbitrary validation block for a key.

We have a resource that is parsed dynamically based on the value of an enum. For validation we use `oneOf` to [provide schemas for each option](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/chart/templates/03-clusterserviceversion.crd.yaml#L319-L411). The backend type for the CR uses `json.RawMessage` so that we can parse differently based on the key value.

This is just a feature request for an escape hatch to let us put arbitrary json-schema for a key, but it might be interesting to think about how to support this pattern more directly in kubebuilder.

**Comment by droot** [comment]
Since CRD schema supports Open API v3, so if Kubebuilder can support `oneOf` directive on the `Go` types (as a function of schema of other backend types you mentioned), this can be addressed I guess.

For custom validation, using ValidatingWebhooks will be more powerful though.

**Comment by Adirio** [comment]
@DirectXMan12 can we freeze the lifecycle of this PR, it will close again in a month.

**Comment by DirectXMan12** [comment]
don't know why you can't do that.  What mortal knows the mind of the CI bot?

**Comment by Adirio** [comment]
> don't know why you can't do that. What mortal knows the mind of the CI bot?

I wasn't a reviewer by that time.

**Comment by DirectXMan12** [comment]
kubernetes-sigs/controller-tools#427 addresses this, at least partially -- types implementing the JSON marshaller/unmarshaller interface will get generated as `type: any` for the base, and further validation can be applied (or not applied) with markers.  I *think* that should largely address the usecase here

**Comment by JohnStarich** [comment]
I'm new to kubebuilder - so we might able to chalk this up to inexperience - but pulling in the commit for https://github.com/kubernetes-sigs/controller-tools/pull/427 doesn't seem to work for me. At least not entirely. The CRDs do generate with `type: Any`, but I can't figure out how to apply a string or integer to that kind of field:
```
➜ /tmp cat test.yaml
apiVersion: ibmcloud.ibm.com/v1beta1
kind: Service
metadata:
  name: myname
spec:
  plan: standard
  serviceClass: myservice
  parameters:
  - name: somenumber
    value: 30720
  - name: someothernumber
    value: 6144
  - name: somestring
    value: private
  - name: somereferencedvalue
    valueFrom:
      secretKeyRef:
        name: xyz
        key: abc
➜ /tmp kubectl apply -f test.yaml
The Service "myname" is invalid:
* spec.parameters.value: Invalid value: "integer": spec.parameters.value in body must be of type Any: "integer"
* spec.parameters.value: Invalid value: "string": spec.parameters.value in body must be of type Any: "string"
➜ /tmp kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.11+IKS", GitCommit:"c33b093e937d1f9eee340f9bddfa14e1e54ad1a4", GitTreeState:"clean", BuildDate:"2020-06-17T21:37:54Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
➜ /tmp
```
Also, for some reason the last two fields generated `null` inside the CRDs, seemingly as a direct result of 427:
```yaml
  conditions: null
  storedVersions: null
```

It's worth noting the CRD works with an older kubebuilder version if we `sed` out the offending `type: object` lines from the auto-generated yaml, but I'd really like to avoid such hackery 😄 

<details>
<summary>Here's my config/crd/bases/*.yaml, if it helps:</summary>


```yaml

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.1-0.20200517180335-820a4a27ea84
  creationTimestamp: null
  name: services.ibmcloud.ibm.com
spec:
  group: ibmcloud.ibm.com
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: Service is the Schema for the services API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ServiceSpec defines the desired state of Service
          properties:
            parameters:
              items:
                description: Param represents a key-value pair
                properties:
                  attributes:
                    additionalProperties:
                      type: Any
                    description: A parameter may have attributes (e.g. message hub
                      topic might have partitions)
                    type: object
                  name:
                    description: Name representing the key.
                    type: string
                  value:
                    description: Defaults to null.
                    type: Any
                  valueFrom:
                    description: Source for the value. Cannot be used if value is
                      not empty.
                    properties:
                      configMapKeyRef:
                        description: Selects a key of a ConfigMap.
                        properties:
                          key:
                            description: The key to select.
                            type: string
                          name:
                            description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                              TODO: Add other useful fields. apiVersion, kind, uid?'
                            type: string
                          optional:
                            description: Specify whether the ConfigMap or its key
                              must be defined
                            type: boolean
                        required:
                        - key
                        type: object
                      secretKeyRef:
                        description: Selects a key of a secret in the resource namespace
                        properties:
                          key:
                            description: The key of the secret to select from.  Must
                              be a valid secret key.
                            type: string
                          name:
                            description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                              TODO: Add other useful fields. apiVersion, kind, uid?'
                            type: string
                          optional:
                            description: Specify whether the Secret or its key must
                              be defined
                            type: boolean
                        required:
                        - key
                        type: object
                    type: object
                required:
                - name
                type: object
              type: array
            plan:
              type: string
            serviceClass:
              type: string
          required:
          - plan
          - serviceClass
          type: object

          ...

      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
```
</details>
