### ISSUE TITLE
kubebuilder:pruning:PreserveUnknownFields  Spec

### ISSUE THREAD

**Issue by zhujintao** [kubernetes-sigs/kubebuilder#3093]
### What broke? What's expected?

deploys_types.go
```
// +kubebuilder:pruning:PreserveUnknownFields
type DeploysSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	AppList []string                       `json:"appsList,omitempty"`
}
```
···

deploy.yaml
```yaml
apiVersion: cy-sys.cn/v1beta1
kind: Deploys
metadata:
  name: cybsprod
  namespace: cybs-prod
spec:
  appsList:
  - t1
  - t2
  tmpPath: /tmp

```
kubectl get deploy -o yaml

```
  spec:
      appsList:
        - t1
        - t2
      tmpPath: /tmp
}
```

kubebuilder:pruning:PreserveUnknownFields DeploysSpec,

 Reconcile logic how to read tmpPath ?

### Reproducing this issue

kubebuilder:pruning:PreserveUnknownFields DeploysSpec

 Reconcile logic how to read tmpPath ?

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.7.0", KubernetesVendor:"1.24.1", GitCommit:"3bfc84ec8767fa760d1771ce7a0cb05a9a8f6286", BuildDate:"2022-09-20T17:21:57Z", GoOs:"linux", GoArch:"amd64"}
