### ISSUE TITLE
CRD short names are overwritten by `make manifests`

### ISSUE THREAD

**Issue by astraw99** [kubernetes-sigs/kubebuilder#3103]
### What broke? What's expected?

In the crd/bases/xxx.yaml，the default generated CRD yaml not include `shortNames` and `categories`, like:
```
spec:
  group: example.com
  names:
    kind: Demo
    listKind: DemoList
    plural: demos
    singular: demo
    categories: # will be overwritten
      - demo
    shortNames: # will be overwritten
      - de
  scope: Namespaced
  versions:
  - name: v1beta1
```
After `make manifests`, the `shortNames` and `categories` will be overwritten.

### Reproducing this issue

1. Create API, then `make manifests`;
2. Modify the crd/bases/xxx.yaml with `shortNames` and `categories` like above;
3. Then `make manifests` again, will reproduce this issue.

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.7.0", KubernetesVendor:"1.24.1", GitCommit:"3bfc84ec8767fa760d1771ce7a0cb05a9a8f6286", BuildDate:"2022-09-20T17:21:57Z", GoOs:"darwin", GoArch:"amd64"}
