### ISSUE TITLE
Incorrect use of k8s recommended labels

### ISSUE THREAD

**Issue by blacksails** [kubernetes-sigs/kubebuilder#3107]
### What broke? What's expected?

kubebuilder 3.7.0 introduced the recommended k8s labels in the kustomize scaffold. This issue is related to the current implementation.

The current implementation doesn't use the labels like they are supposed to be used documented at https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/.

The labels are supposed to group resources as applications and instances of these.

- `app.kubernetes.io/name` should be used for the name of the application. 3.7.0 implementation uses it to hold the k8s resource name
- `app.kubernetes.io/instance` should be used for a unique name of an instance of the application. 3.7.0 implementation uses it to hold a descriptive name of the k8s resource.

Apart from the two above, the rest of the labels are less important. But using the recommended labels is quite useless if the above two labels are not used correctly. If some of the remaining labels don't make sense in the usecase they should simply be exempt.

In a typical kubebuilder project I would expect the following labels on all resources:

```yaml
apiVersion: <api-version>
kind: <resource>
metadata:
  labels:
    app.kubernetes.io/name: <project-name>
    app.kubernetes.io/instance: <instance-name>
    app.kubernetes.io/version: <project-version>
    app.kubernetes.io/managed-by: kustomize
```

I dont really see `app.kubernetes.io/component` and `app.kubernetes.io/part-of` being relevant.

Further more to simplify one could use kustomize to set the labels across all resources. https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/labels/

### Reproducing this issue

`kubebuilder init` and look at the generated kubernetes resources in the config folder

### KubeBuilder (CLI) Version

3.7.0

**Comment by camilamacedo86** [comment]
HI @blacksails, 

According to the docs: 

<img width="812" alt="Screenshot 2022-12-02 at 15 24 21" src="https://user-images.githubusercontent.com/7708031/205327006-3d821dce-7cab-4f35-9ab1-691c5242dc2e.png">

Then are you speaking about the CRs?
So, let's check an example:

```
apiVersion: crew.testproject.org/v1
kind: Admiral
metadata:
  labels:
    app.kubernetes.io/name: mysql ->(  Kind/API which is the name of the "äpplication/service" that will be represented by the endpoint/api i.e MySQL such as the doc example ) 
    app.kubernetes.io/instance: mysql-sample (Cr name -> unique instance name )
    app.kubernetes.io/part-of: mysql-operator (Name of the project)
    app.kubernetes.io/managed-by: kustomize (because it is managed by kustomized)
    app.kubernetes.io/created-by: mysql-operator (name of the project)
```

So, I understand that the only annotation that you do not agree with is `app.kubernetes.io/name: `. In your POV that should be the name of the project. However, if you look at the example in this doc I think we can clarify that is the name of the App/Service and in this case the Kind/CRD/Endpoint. (Please, see check the doc [Groups and Versions and Kinds, oh my!](https://book.kubebuilder.io/cronjob-tutorial/gvks.html) )

So, let's check the doc examples:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mysql ( name of the Kind/Type/App/Service) 
    app.kubernetes.io/instance: mysql-abcxzy
    app.kubernetes.io/version: "5.7.21"
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress ( name of the project ) 
...
```
More, one example :-) 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: myservice -> See the name of the APP/Service/Kind/Type
    app.kubernetes.io/instance: myservice-abcxzy -> The name of the instance CR
```

Let's check another example in the doc:

```
The Service is used to expose the application.

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: myservice`-> Name of the service (That would be the Kind Again)
    app.kubernetes.io/instance: myservice-abcxzy -> ( that is the name of the CR again )
```

Therefore, ihmo how it has been scaffolded shows following the best practices described in docs. Note that you can have many Kinds/Apis/CRDs and as you can check in the examples it would not make sense to be the project name. Please, let us know if that makes sense and if you agree in close this one.
