### ISSUE TITLE
Kubebuilder go/v4 plugin does create expected folder structure

### ISSUE THREAD

**Issue by Sijoma** [kubernetes-sigs/kubebuilder#3154]
### What broke? What's expected?

The folder layout is not working as expected when using the go/v4-alpha plugin. 

Note the "api" folder is still named "apis" and there is no internal folder for the controllers. 

![image](https://user-images.githubusercontent.com/8970764/211774331-9b29a6f7-3b68-454d-ae2d-506d0e0cc975.png)

Another notable things why it broke first was that I had missing "--" copied from the kubebuilder book. PR to fix this is here: https://github.com/kubernetes-sigs/kubebuilder/pull/3153 

However, I cannot make the new folder structure work.

### Reproducing this issue

kubebuilder init --domain my.domain --plugins=go/v4-alpha 

kubebuilder edit --multigroup=true --plugins=go/v4-alpha

kubebuilder create api --group group --version v1alpha1 --kind MyKind --namespaced=false --plugins=go/v4-alpha  

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:“3.8.0”, KubernetesVendor:“unknown”, GitCommit:“184ff7465947ced153b031db8de297a778cecf36”, BuildDate:“2022-12-02T15:43:53Z”, GoOs:“darwin”, GoArch:“arm64"}

### PROJECT version

New project

### Plugin versions

```yaml
domain: mydomain 
layout:
- go.kubebuilder.io/v4-alpha
multigroup: true
projectName: projectName
repo: github.com/org/repo
resources:
- api:
    crdVersion: v1
  controller: true
  domain: mydomain 
  group: mygroup
  kind: MyKind
  path: github.com/org/repo/apis/mygroup/v1alpha1
  version: v1alpha1
version: "3"
```

### Other versions

go version go1.19.4 darwin/arm64

go env:

> GO111MODULE=""
> GOARCH="arm64"
> GOBIN=""
> GOCACHE="/Users/simon/Library/Caches/go-build"
> GOENV="/Users/simon/Library/Application Support/go/env"
> GOEXE=""
> GOEXPERIMENT=""
> GOFLAGS=""
> GOHOSTARCH="arm64"
> GOHOSTOS="darwin"
> GOINSECURE=""
> GOMODCACHE="/Users/simon/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="darwin"
> GOPATH="/Users/simon/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/opt/homebrew/Cellar/go/1.19.4/libexec"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.4/libexec/pkg/tool/darwin_arm64"
> GOVCS=""
> GOVERSION="go1.19.4"
> GCCGO="gccgo"
> AR="ar"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD="/dev/null"
> GOWORK=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dc/dtv0j9t138db5fn4sf9q1dvw0000gn/T/go-build3768419948=/tmp/go-build -gno-record-gcc-switches -fno-common"
