### ISSUE TITLE
rules[0].apiGroups: Required value: resource rules must supply at least one api group

### ISSUE THREAD

**Issue by fungaren** [kubernetes-sigs/kubebuilder#3192]
### What broke? What's expected?

I want to manage Secrets, and the api group of Secrets is empty, so I add this:

```go
//+kubebuilder:rbac:resources=secrets,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:resources=secrets/status,verbs=get
```

Make manifests, the output is:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

But this is invalid, if you try applying it, kubectl will complain:

```text
...
rules[0].apiGroups: Required value: resource rules must supply at least one api group
```

But this doesn't work:

```go
//+kubebuilder:rbac:groups=,resources=secrets,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=,resources=secrets/status,verbs=get
```

This works:

```go
//+kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups="",resources=secrets/status,verbs=get
```

The output is:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

I think we can make it more tolerant. If `apigourp` is not provided or empty, let it output `apiGroups: [""]`

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.9.0", KubernetesVendor:"1.26.0", GitCommit:"26f605e889b2215120f73ea42b081efac99f5162", BuildDate:"2023-01-16T17:21:30Z", GoOs:"darwin", GoArch:"arm64"}

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v4-alpha
```

### Other versions

```yaml
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0+k3s2", GitCommit:"f0ec6a4c127b2c671b271974a2f21783f0e3c525", GitTreeState:"clean", BuildDate:"2023-01-11T21:27:23Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0+k3s2", GitCommit:"f0ec6a4c127b2c671b271974a2f21783f0e3c525", GitTreeState:"clean", BuildDate:"2023-01-11T21:27:23Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/arm64"}
```

**Comment by harshanarayana** [comment]
@fungaren  The Generation is actually done as part of the `controller-gen` and the code to generate that RBAC is under [RBAC Parser](https://github.com/kubernetes-sigs/controller-tools/blob/3379659e724f9f7d1bd414bb05733e681d46b535/pkg/rbac/parser.go#L130)

If you check, there is a special case of group called `core` that translates into `apiGroups: [""]`

So, technically, you can put 

```bash
//+kubebuilder:rbac:groups=core,resources=secrets,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=core,resources=secrets/status,verbs=get
```
below on your code and it will generate the right things for RBAC

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
```
