### ISSUE TITLE
Non-namespaced resource CRD gets generated as scope: Namespaced

### ISSUE THREAD

**Issue by bwarminski** [kubernetes-sigs/kubebuilder#322]
Command Issued:

```
kubebuilder create api --group bigthicket --kind EphemeralEnvironment --namespaced false --version v1alpha1
```

Resulting crd:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: ephemeralenvironments.bigthicket.localytics.com
spec:
  group: bigthicket.localytics.com
  names:
    kind: EphemeralEnvironment
    plural: ephemeralenvironments
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
```

Expected `scope: Cluster`
