### ISSUE TITLE
Kubebuilder generating validating webhook config even when not specified, kustomize does not work

### ISSUE THREAD

**Issue by xagent003** [kubernetes-sigs/kubebuilder#3304]
### What broke? What's expected?

Is this perhaps a bug with kubebuilder? I generated a webhook with only defaulting. 

Error: no matches for Id ValidatingWebhookConfiguration.v1.admissionregistration.k8s.io/validating-webhook-configuration.[noNs]; failed to find unique target for patch ValidatingWebhookConfiguration.v1.admissionregistration.k8s.io/validating-webhook-configuration.[noNs]

I noticed the config/webhook/kustomizeconfig.yaml refers to a ValidatingWebhookConfiguration:

```
# the following config is for teaching kustomize where to look at when substituting vars.
# It requires kustomize v2.1.0 or newer to work properly.
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - kind: MutatingWebhookConfiguration
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/service/name
  - kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/service/name

namespace:
- kind: MutatingWebhookConfiguration
  group: admissionregistration.k8s.io
  path: webhooks/clientConfig/service/namespace
  create: true
- kind: ValidatingWebhookConfiguration
  group: admissionregistration.k8s.io
  path: webhooks/clientConfig/service/namespace
  create: true

varReference:
- path: metadata/annotations
```

I also see a ValidatingWebhookConfiguration resource defined in config/default/wehbookcainjection_patch.yaml

### Reproducing this issue

Generate a kubebuilder controller and webhook only for defaulting. Deploy cert-manager then follow steps here to uncomment webhook resources: https://book.kubebuilder.io/cronjob-tutorial/running-webhook.html

You will see make deploy error's out on the kustomize stage.

I saw validatingwebhook kustomize resources and patches were still generated, I had to comment them out for it to work

### KubeBuilder (CLI) Version

3.9.1

### PROJECT version

3

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v3
```

### Other versions

Go 1.19
k8s 1.24

**Comment by xiao-jay** [comment]
I found that there is indeed a problem
```
i uncomment webhook
//+kubebuilder:webhook:path=/mutate-batch-tutorial-kubebuilder-io-v1-cronjob,mutating=true,failurePolicy=fail,sideEffects=None,groups=batch.tutorial.kubebuilder.io,resources=cronjobs,verbs=create;update,versions=v1,name=mcronjob.kb.io,admissionReviewVersions=v1
//+kubebuilder:webhook:path=/validate-batch-tutorial-kubebuilder-io-v1-cronjob,mutating=false,failurePolicy=fail,sideEffects=None,groups=batch.tutorial.kubebuilder.io,resources=cronjobs,verbs=create;update,versions=v1,name=vcronjob.kb.io,admissionReviewVersions=v1
```

run `make install && make manifests && make generate `

config/webhook/kustomizeconfig.yaml still have config.
```
# the following config is for teaching kustomize where to look at when substituting vars.
# It requires kustomize v2.1.0 or newer to work properly.
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - kind: MutatingWebhookConfiguration
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/service/name
  - kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/service/name

namespace:
- kind: MutatingWebhookConfiguration
  group: admissionregistration.k8s.io
  path: webhooks/clientConfig/service/namespace
  create: true
- kind: ValidatingWebhookConfiguration
  group: admissionregistration.k8s.io
  path: webhooks/clientConfig/service/namespace
  create: true

varReference:
- path: metadata/annotations

```

```
➜  test2 kubebuilder version
Version: main.version{KubeBuilderVersion:"v3.9.0-48-g73e25fad-dirty", KubernetesVendor:"unknown", GitCommit:"73e25fadb93daa1e240b4dda4df7c9016ef4d3ce", BuildDate:"2023-03-04T05:50:09Z", GoOs:"darwin", GoArch:"arm64"}

```
