### ISSUE TITLE
Generated rbac rules lack API group domain

### ISSUE THREAD

**Issue by sttts** [kubernetes-sigs/kubebuilder#338]
I have generated a project with:

```shell
$ kubebuilder init --domain k8s-go.openshift.org --license apache2 --owner "The workshop members"
$ kubebuilder create api --group policy --version v1beta1 --kind HealthCheckPolicy
```

The generated rbac role is wrong (lacks the `k8s-go.openshift.org` domain):

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - policy
  resources:
  - healthcheckpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
```
