### ISSUE TITLE
Invalid Kustomize generation 

### ISSUE THREAD

**Issue by lauchokyip** [kubernetes-sigs/kubebuilder#3425]
### What broke? What's expected?

This PR (https://github.com/kubernetes-sigs/kubebuilder/pull/3374) breaks the kustomization files generated. Had to revert back to `patchesStrategicMerge`

To reproduce:
1)
```bash
mkdir testing
cd testing
kubebuilder init --domain tutorial.kubebuilder.io --repo tutorial.kubebuilder.io/project
kubebuilder create api --group batch --version v1 --kind CronJob
kubebuilder create webhook --group batch --version v1 --kind CronJob  --conversion
make manifests
```
2) Go to `/config/crd/kustomization.yaml` and uncomment 
```yaml
patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_cronjobs.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_cronjobs.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch
```
3) Run `kustomize` against it
```
kustomize build config/crd
Error: invalid Kustomization: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patc
```

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"v3.10.0-57-g959952de-dirty", KubernetesVendor:"unknown", GitCommit:"959952decffecb9a35bb843e706849586883360c", BuildDate:"2023-05-16T02:27:25Z", GoOs:"linux", GoArch:"amd64"}

**Comment by camilamacedo86** [comment]
@Sajiyah-Salat,

We need to check the kustomize documentation and see what is missing to get it fixed.
Otherwise we need to revert prior release.

**Comment by erikgb** [comment]
I think we are just missing a key in the patches array elements. It should look like this, I think:

````yaml
patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_cronjobs.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_cronjobs.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch
````
