### ISSUE TITLE
Controller test suite will not work with types from aggregated API server

### ISSUE THREAD

**Issue by jpeeler** [kubernetes-sigs/kubebuilder#362]
The documentation should be updated to make it clear that types provided via an aggregated api server (in this case service-catalog) is not expected to work. I discovered this when trying to get a resource and received a meta.NoKindMatchError. It'd be nice if in the future scaffolding could be provided to start an additional api server during tests so this scenario would be possible.

**Comment by jkev53** [comment]
The solution that I have come up with is to add code to Register the types in the pkg/apis directory.
```
package apis

import (
	foov1alpha1 "github.com/jkevlin/apis/foo/v1alpha1"
	"sigs.k8s.io/controller-runtime/pkg/runtime/scheme"
)

func init() {
	// Register the types with the Scheme so the components can map objects
	// to GroupVersionKinds and back
	localSchemeBuilder := &scheme.Builder{GroupVersion: foov1alpha1.SchemeGroupVersion}
	localSchemeBuilder.Register(&foov1alpha1.Bar{}, &foov1alpha1.BarList{})
	AddToSchemes = append(AddToSchemes, foov1alpha1.AddToScheme)
}
```
Also, you must create a config/crds/foo_customresource.yaml
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: bars.foo.example.com
spec:
  group: foo.example.com
  names:
    kind: Bar
    plural: bars
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
```

With this done both `make test` and `make run` work
