### ISSUE TITLE
BeforeSuite and AfterSuite modules not running in the ginkgo v2

### ISSUE THREAD

**Issue by dashanji** [kubernetes-sigs/kubebuilder#3646]
### What broke? What's expected?

What broke? 
The BeforeSuite and AfterSuite modules not running in the ginkgo v2. In other words, the current `make test` do nothing in all project with the ginkgo v2.
Refer to the [ginkgo v2.0 note](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#minor-additions-and-improvements), the BeforeSuite and AfterSuite will not run if all tests in a suite are skipped.

What's expected?
In the project with the ginkgo v2, the `make test` command can run successfully as expected and do the operations such as installing CRD actually.

### Reproducing this issue

1. Move into a test-project with ginkgo v1.
```bash
$ cd project
```

Add a wrong assertion as follows.
```yaml
var _ = BeforeSuite(func(done Done) {
    Expect(1).To(Equal(2))
}, 60)

var _ = AfterSuite(func() {
    Expect(1).To(Equal(2))
})
```

Run `make test`, and you will get some errors because the BeforeSuite module **executed actually**.

2. Move into a test-project with ginkgo v1.
```bash
$ cd project/testdata/project-v4
```

Add a wrong assertion as follows.
```yaml
var _ = BeforeSuite(func() {
    Expect(1).To(Equal(2))
})
```

Run `make test`, and you will run successfully because the BeforeSuite module **not executed actually**.

### KubeBuilder (CLI) Version

3.12.0

### PROJECT version

3

### Plugin versions

```yaml
# Code generated by tool. DO NOT EDIT.
# This file is used to track the info used to scaffold your project
# and allow the plugins properly work.
# More info: https://book.kubebuilder.io/reference/project-config.html
domain: testproject.org
layout:
- go.kubebuilder.io/v4
projectName: project-v4
repo: sigs.k8s.io/kubebuilder/testdata/project-v4
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: testproject.org
  group: crew
  kind: Captain
  path: sigs.k8s.io/kubebuilder/testdata/project-v4/api/v1
  version: v1
  webhooks:
    defaulting: true
    validation: true
    webhookVersion: v1
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: testproject.org
  group: crew
  kind: FirstMate
  path: sigs.k8s.io/kubebuilder/testdata/project-v4/api/v1
  version: v1
  webhooks:
    conversion: true
    webhookVersion: v1
- api:
    crdVersion: v1
  controller: true
  domain: testproject.org
  group: crew
  kind: Admiral
  path: sigs.k8s.io/kubebuilder/testdata/project-v4/api/v1
  plural: admirales
  version: v1
  webhooks:
    defaulting: true
    webhookVersion: v1
- controller: true
  domain: testproject.org
  group: crew
  kind: Laker
  version: v1
version: "3"
```
