### ISSUE TITLE
duplicited CRD in dist/install.yaml

### ISSUE THREAD

**Issue by lukas016** [kubernetes-sigs/kubebuilder#3767]
### What broke? What's expected?

current make build-install generate dist/install.yaml from config/crd and config/default.
config/default  internally use config/crd too. Result are 2 same definitions of CRD in dist/install.yaml

```
cat -n dist/install.yaml| grep 'Test'
    10	    kind: Test
    11	    listKind: TestList
    19	        description: Test is the Schema for the tests API
    39	            description: TestSpec defines the desired state of Test
    42	                description: Foo is an example field of Test. Edit test_types.go to
    47	            description: TestStatus defines the observed state of Test
    77	    kind: Test
    78	    listKind: TestList
    86	        description: Test is the Schema for the tests API
   106	            description: TestSpec defines the desired state of Test
   109	                description: Foo is an example field of Test. Edit test_types.go to
   114	            description: TestStatus defines the observed state of Test
```

### Reproducing this issue

1. Use CRD in project
2. Call make build-installer
3. Find duplicity in dist/install.yaml

### KubeBuilder (CLI) Version

master

### PROJECT version

3

**Comment by lukas016** [comment]
@camilamacedo86 can we continue in discussion here because current implementation has problem with duplication of CRDs.

Do you want to generate CRD always independently on config/default?

**Comment by camilamacedo86** [comment]
Hi @lukas016,

Feel free to check it and provide a solution that works
The goal is to generate the YAML (bundle) with all required/scaffolds to install/distribute the Operator.

**Comment by antonosmond** [comment]
Just to add to this, if you use webhooks, the duplicated CRDs are actually different.
If you run `make build-installer`, the make command is creating the first copy of the CRD with:

```sh
$(KUSTOMIZE) build config/crd > dist/install.yaml
``` 

In this version the `webhook.clientConfig` won't have the `namePrefix` or `namespace` override.

The second copy of the CRD is generated with:

```sh
$(KUSTOMIZE) build config/default >> dist/install.yaml
```

The `config/default/kustomization.yaml` includes `- ../crd` but this version does patch the `webhook.clientConfig` so you end up with 2 conflicting copies of the CRD, one unpatched e.g: 

```yaml
    webhook:
      clientConfig:
        service:
          name: webhook-service
          namespace: system
          path: /convert
```

and the other patched e.g.

```yaml
    webhook:
      clientConfig:
        service:
          name: blueprint-controller-webhook-service
          namespace: kloudy-system
          path: /convert

```
