### ISSUE TITLE
RBAC for `get` on status subresource is unnecessary

### ISSUE THREAD

**Issue by joelanford** [kubernetes-sigs/kubebuilder#3781]
### What broke? What's expected?

I created an API and Kubebuilder generated editor and viewer cluster roles for me. I notice that the scaffolding code includes a rule like:
```yaml
- apiGroups:
   - example.com
   resources:
   - widgets/status
   verbs:
   - get
```

As far as I can tell, there is no `get` verb on the status subresource. Just `update` and `patch`.

### Reproducing this issue

Run `kubebuilder create api` with any input that results in an API being successfully created in a project.

### KubeBuilder (CLI) Version

`master`

### PROJECT version

N/A

### Plugin versions

```yaml
Looks like this is present in kustomize/v1, kustomize/v2, golang/v3, and golang/v2.
```

### Extra Labels

/kind cleanup
