### ISSUE TITLE
kubebuilder make install fails [again]: metadata.annotations: Too long

### ISSUE THREAD

**Issue by ep4sh** [kubernetes-sigs/kubebuilder#3903]
### What broke? What's expected?

Hi team, I'm trying to install CRD into the k8s kind cluster v1.29.2 but getting the know error.

```
 project (master) pwd
/home/ep4sh/go/src/kubebuilder/docs/book/src/cronjob-tutorial/testdata/project

 project (master) make manifests
/home/ep4sh/go/src/kubebuilder/docs/book/src/cronjob-tutorial/testdata/project/bin/controller-gen-v0.14.0 rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases

 project (master) k get nodes
NAME                 STATUS   ROLES           AGE   VERSION
kind-control-plane   Ready    control-plane   11m   v1.29.2

 project (master) make install
/home/ep4sh/go/src/kubebuilder/docs/book/src/cronjob-tutorial/testdata/project/bin/controller-gen-v0.14.0 rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/ep4sh/go/src/kubebuilder/docs/book/src/cronjob-tutorial/testdata/project/bin/kustomize-v5.3.0 build config/crd | kubectl apply -f -
The CustomResourceDefinition "cronjobs.batch.tutorial.kubebuilder.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
make: *** [Makefile:131: install] Error 1


```
I walked through some closed issues like: https://github.com/kubernetes-sigs/kubebuilder/pull/2862

As I can see the history of the file, the desired option `crd:maxDescLen=0` was removed:
https://github.com/kubernetes-sigs/kubebuilder/commit/c10168fd442d25167b3f92d2463e497cb3d15af5

is that an error of my environment?
Thanks

### Reproducing this issue

```
git clone https://github.com/kubernetes-sigs/kubebuilder.git
cd kubebuilder/docs/book/src/cronjob-tutorial/testdata/project
make manifests
make install
```

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.14.2", KubernetesVendor:"1.27.1", GitCommit:"d7b4febe6b673709100b780b5b99151c5e26a206", BuildDate:"2024-04-27T08:27:24Z", GoOs:"linux", GoArch:"amd64"}

### PROJECT version

version: "3"

### Plugin versions

```yaml
project (master) cat PROJECT 
# Code generated by tool. DO NOT EDIT.
# This file is used to track the info used to scaffold your project
# and allow the plugins properly work.
# More info: https://book.kubebuilder.io/reference/project-config.html
domain: tutorial.kubebuilder.io
layout:
- go.kubebuilder.io/v4
projectName: project
repo: tutorial.kubebuilder.io/project
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: tutorial.kubebuilder.io
  group: batch
  kind: CronJob
  path: tutorial.kubebuilder.io/project/api/v1
  version: v1
  webhooks:
    defaulting: true
    validation: true
    webhookVersion: v1
version: "3"

```
```


### Other versions

```
 project (master) go version
go version go1.22.3 linux/amd64
```
k8s kind:
```
 project (master) k get nodes
NAME                 STATUS   ROLES           AGE   VERSION
kind-control-plane   Ready    control-plane   11m   v1.29.2
```

### Extra Labels

_No response_
