### ISSUE TITLE
Why set namespace with kustomize for cluster-scoped Mutating|ValidatingWebhookConfiguration?

### ISSUE THREAD

**Issue by davidxia** [kubernetes-sigs/kubebuilder#3999]
## What "broke"

Why does kubebuilder use a [namespace kustomization transformer](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#namespace) to set a namespace for Mutating|ValidatingWebhookConfiguration if these are cluster-scoped resources? [Code here](https://github.com/kubernetes-sigs/kubebuilder/blob/79cec87ec5d2e0a594a15caac1fe5693d1225e66/pkg/plugins/golang/v2/scaffolds/internal/templates/config/webhook/kustomizeconfig.go#L59-L67)

Isn't this unnecessary?

## What's expected

IIUC, lines of code above shouldn't exist as they don't do anything?

### Expected output

```
# the following config is for teaching kustomize where to look at when substituting vars.
# It requires kustomize v2.1.0 or newer to work properly.
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - kind: MutatingWebhookConfiguration
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/service/name
  - kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/service/name

varReference:
- path: metadata/annotations
```

### Actual output

```
# the following config is for teaching kustomize where to look at when substituting vars.
# It requires kustomize v2.1.0 or newer to work properly.
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - kind: MutatingWebhookConfiguration
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/service/name
  - kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/service/name

namespace:
- kind: MutatingWebhookConfiguration
  group: admissionregistration.k8s.io
  path: webhooks/clientConfig/service/namespace
  create: true
- kind: ValidatingWebhookConfiguration
  group: admissionregistration.k8s.io
  path: webhooks/clientConfig/service/namespace
  create: true

varReference:
- path: metadata/annotations
```

### Reproducing this issue

Run `kubebuilder create webhook --group batch --version v1 --kind CronJob --defaulting --programmatic-validation` as described in [Implementing defaulting/validating webhooks](https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation#implementing-defaultingvalidating-webhooks).

### KubeBuilder (CLI) Version

4.0.0

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v4
```

### Other versions

go 1.22.2
sigs.k8s.io/controller-runtime v0.18.2

kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3-gke.1282000

### Extra Labels

/kind cleanup
