### ISSUE TITLE
 Add kubebuilderVersion Field in PROJECT File for Tracking Kubebuilder CLI Version

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#4398]
### What do you want to happen?

**Description:**  
To enhance project traceability and facilitate future upgrades, it's proposed that Kubebuilder's `PROJECT` file includes a new field, `kubebuilderVersion`, to record the specific CLI version used during project scaffolding. This addition will:

- Help identify the tooling version employed, aiding in troubleshooting and ensuring compatibility with updates.
- Provide developers with clearer insights into their project's setup for efficient maintenance and evolution.
- Support solutions like [PR #4302](https://github.com/kubernetes-sigs/kubebuilder/pull/4302) and align with broader goals for traceability and user support.

**Tasks:**
1. Add a new field in the `PROJECT` file: `kubebuilderVersion`.
2. Ensure the field tracks the Kubebuilder tool version used during scaffolding.
3. Update the documentation in the [Project Configuration Reference](https://book.kubebuilder.io/reference/project-config) to include the new `kubebuilderVersion` field.

**Reference Files:**  
- Example `PROJECT` file: [PROJECT File](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/PROJECT)  
- Documentation: [Project Config Docs](https://book.kubebuilder.io/reference/project-config)  

This change aims to improve traceability and simplify workflows for users and maintainers.

**Comment by camilamacedo86** [comment]
We are open to better name suggestions as well !!

**Comment by rovertrack** [comment]
can i try to solve this

**Comment by mateusoliveira43** [comment]
@rovertrack just comment here `/assign` and the issue will be assigned to you (so that 2 people do not work on the same task)

if you need any help, just ping here or in the PR

**Comment by rovertrack** [comment]
where the kubebuilderVersion has to be in the projectfile

**Comment by mateusoliveira43** [comment]
currently, a sample PROJECT file looks like this
```yaml
# Code generated by tool. DO NOT EDIT.
# This file is used to track the info used to scaffold your project
# and allow the plugins properly work.
# More info: https://book.kubebuilder.io/reference/project-config.html
domain: openshift.io
layout:
- go.kubebuilder.io/v4
projectName: oadp-nac
repo: github.com/migtools/oadp-non-admin
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: openshift.io
  group: oadp
  kind: NonAdminBackup
  path: github.com/migtools/oadp-non-admin/api/v1alpha1
  version: v1alpha1
version: "3"
```

I think it makes sense to be a high level information, like `version`

It would look like this then
```yaml
# Code generated by tool. DO NOT EDIT.
# This file is used to track the info used to scaffold your project
# and allow the plugins properly work.
# More info: https://book.kubebuilder.io/reference/project-config.html
domain: openshift.io
layout:
- go.kubebuilder.io/v4
projectName: oadp-nac
repo: github.com/migtools/oadp-non-admin
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: openshift.io
  group: oadp
  kind: NonAdminBackup
  path: github.com/migtools/oadp-non-admin/api/v1alpha1
  version: v1alpha1
version: "3"
kubebuilderVersion: "3.14.2"
```
