### ISSUE TITLE
Enhance Test for kubebuilder alpha generate Command

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#4508]
### What do you want to happen?

We need to enhance the testing of the `kubebuilder alpha generate` command.  For further information see: https://book.kubebuilder.io/reference/rescaffold

Note that under the testdata we scaffold samples: 
- testdata dir: https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata
- code used to generate the samples: https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/testdata/generate.sh

The goal here is to validate its functionality for all samples under testdata. A shell script solution is acceptable for this purpose, but if a better approach using Go tests (leveraging the existing test framework) can be implemented to validate the PROJECT file content, it would be preferable. Currently, the command is tested under: [e2e/alphagenerate](https://github.com/kubernetes-sigs/kubebuilder/tree/master/test/e2e/alphagenerate). This enhancement aims to:

Therfore what we need to do is:
- A CI test that will execute kubebuilder alpha generate inside of each sample under the testdata dir
- The command should be finished without errors
- (Optionally and if we find an easy way to do it maintainable ): Verify that the PROJECT file has the same webhooks and APIs as the original.

**Comment by camilamacedo86** [comment]
In this case, what we probably want is:

1. **Shell Script**:
   - Create a shell script and place it under:  
     [`test`](https://github.com/kubernetes-sigs/kubebuilder/tree/master/test).
   - The script will contain logic to call the relevant command for all directories under the `testdata` directory.

**Example**

   ```bash
   # Example shell script logic
   for dir in testdata/*; do
       # Call alpha-generate to validate the re-generation of all samples
       $kb alpha generate    
   done
```

2. **Makefile Target**:
   - Add a new target to the `Makefile`, similar to [these examples](https://github.com/kubernetes-sigs/kubebuilder/blob/master/Makefile#L158-L161).
   - This target will be named something like `test-alpha-generate`.

**Example**

   ```make
   test-alpha-generate:
       ./test/alpha-generate.sh
   ``` 

 3. **CI Integration**:
   - Update the CI/GitHub workflows located at:  
     [`.github/workflows`](https://github.com/kubernetes-sigs/kubebuilder/tree/master/.github/workflows).
   - Create a new GitHub Action, e.g., `test-alpha-generate`.
   - Configure the action to run only when changes occur in the following paths:
     - [`pkg/cli/alpha`](https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/cli/alpha)
     - The new shell script file
     - The workflow or GitHub Action itself

**Example**

   ```yaml
   name: Test Alpha Generate

   on:
     push:
       paths:
         - 'pkg/cli/alpha/**'
         - 'test/alpha-generate.sh'
         - '.github/workflows/alpha-generate.yml'
     pull_request:
       paths:
         - 'pkg/cli/alpha/**'
         - 'test/**'
         - '.github/workflows/**'

   jobs:
     test-alpha-generate:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v5
         - name: Run test-alpha-generate
           run: make test-alpha-generate
    ```
