### ISSUE TITLE
Kubebuilder scaffolding with HTTPS endpoint for metrics endpoint with custom certs doesn't work

### ISSUE THREAD

**Issue by abhishekdwivedi3060** [kubernetes-sigs/kubebuilder#4533]
### What broke? What's expected?

Broken:
Metrics server with HTTPS and cert-manager certs doesn't work
1. `config/prometheus/monitor_tls_patch.yaml` path completely overwrites the ServiceMonitor `endpoints` field, resulting in omission of existing fields like `path`, `scheme` etc
2. Prometheus is not able to validate the metric server certificate because it is connecting all underlying service pods over POD IP whereas certificate SANs have metrics service names. So it’s not able to validate the host authenticity.  Its throwing error:
```
x509: cannot validate certificate for 10.20.5.28 because it doesn't contain any IP SANs
```
PFA screenshot for the same:

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/819b9557-e1ae-4ae4-9c71-c460fa04ed44" />

Expected:
1. `config/prometheus/monitor_tls_patch.yaml` patch should only update the `tlsConfig` field with the required certs, leaving all existing fields intact.
2.  Prometheus should be able to validate the metrics server certs and scrape the metrics successfully. 

### KubeBuilder (CLI) Version

4.4.0

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v4
```

**Comment by abhishekdwivedi3060** [comment]
Workaround/fix for now (until this is fixed) :
1. Manually add the old omitted fields in the ServiceMonitor file.
2. Add `serverName` in the `tlsConfig` so that Prometheus can validate the metrics server cert SANs entries

The resultant ServiceMonitor file will look like this:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: operator
    control-plane: controller-manager
  name: controller-manager-metrics-monitor
spec:
  endpoints:
    - path: /metrics
      interval: 15s
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        serverName: operator-controller-manager-metrics-service.default.svc  # dnsNames from the metrics-certs Certificate
        ca:
          secret:
            key: ca.crt
            name: metrics-server-cert
        cert:
          secret:
            key: tls.crt
            name: metrics-server-cert
        insecureSkipVerify: false
        keySecret:
          key: tls.key
          name: metrics-server-cert
  selector:
    matchLabels:
      control-plane: controller-manager
```
