### ISSUE TITLE
Missing RBAC for controller-manager ServiceAccount to access /metrics endpoint in kubebuilder scaffolding

### ISSUE THREAD

**Issue by animesh-agarwal** [kubernetes-sigs/kubebuilder#4805]
### What broke? What's expected?

I followed the [Kubebuilder metrics documentation](https://book.kubebuilder.io/reference/metrics.html) to enable metrics for my controller built using Operator SDK scaffolding. The default Kubebuilder scaffolding for metrics integration does not bind the controller-manager ServiceAccount to the metrics-reader ClusterRole. As a result, even though the metrics endpoint is available and authenticated requests are made, access is denied with a 403 Forbidden error.

Expected Behavior:
When following Kubebuilder's documentation to expose metrics, the controller-manager ServiceAccount should have appropriate RBAC permissions (e.g., via metrics-reader ClusterRoleBinding) to access the /metrics endpoint without manual intervention. The request is being authenticated, but the service account lacks the necessary RBAC permissions to access the /metrics endpoint. 

### Reproducing this issue

- Scaffold a new controller using Kubebuilder or Operator SDK (which is based on Kubebuilder).
- Follow the standard process to expose metrics (no custom RBAC additions).
- Deploy a pod in the same namespace using the controller-manager ServiceAccount to simulate Prometheus scraping the /metrics endpoint. 
       
 ``` 
        apiVersion: v1
        kind: Pod
        metadata:
          name: metrics-consumer
          namespace: system
        spec:
          serviceAccountName: controller-manager
          containers:
          - name: metrics-consumer
            image: curlimages/curl:latest
            command: ["/bin/sh"]
            args:
              - "-c"
              - >
                while true;
                do
                  curl -s -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
                  https://controller-manager-metrics-service.system.svc.cluster.local:8443/metrics;
                  sleep 60;
                done 
```

**Possible solution**
The metrics-reader ClusterRole provides access to /metrics, but it is not bound by default to the controller’s service account. This needs to be added manually:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-metrics-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-reader
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
```

If this is confirmed as a bug, I’d be happy to raise a PR to address it. 

### KubeBuilder (CLI) Version

I am using operator-sdk which is using kubebuilder. 

### PROJECT version

3

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v4
plugins:
  manifests.sdk.operatorframework.io/v2: {}
  scorecard.sdk.operatorframework.io/v2: {}
```

### Other versions

go version go1.23.6 darwin/amd64

kubectl version:
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.7
