### ISSUE TITLE
(helm/v1-alpha) Incorrect service name for conversion webhook

### ISSUE THREAD

**Issue by fhirscher** [kubernetes-sigs/kubebuilder#4807]
### What broke? What's expected?

If you use the Helm plugin and define a conversion webhook, a non-existent service for the conversion webhook is defined in the CRD of the Helm chart.

### Reproducing this issue

Create a project with the helm/v1-alpha plugin and a multi-version API with a convention webhook.

The convention webhook in the CRD in the Helm chart looks like this:
```
...
spec:
  {{- if .Values.webhook.enable }}
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: {{ .Release.Namespace }}
          name: webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
  {{- end }}
...
```

The service name should also contain the project name:
```
...
spec:
  {{- if .Values.webhook.enable }}
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: {{ .Release.Namespace }}
          name: project-v4-with-plugins-webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
  {{- end }}
...
```

### KubeBuilder (CLI) Version

v4.5.2

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v4
helm.kubebuilder.io/v1-alpha
```
