### ISSUE TITLE
Proposal: Integrate kube-api-linter into Kubebuilder via golangci-lint

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#4809]
### Proposal: Integrate [`kube-api-linter`](https://github.com/kubernetes-sigs/kube-api-linter) into Kubebuilder

[`kube-api-linter`](https://github.com/kubernetes-sigs/kube-api-linter) is a custom linter designed to enforce Kubernetes API conventions and best practices. Since Kubebuilder is centered around building Kubernetes APIs and controllers, enforcing these standards early in the development process can help ensure high-quality, compliant APIs.

Integrating it into our tooling would provide users with immediate feedback about common issues or violations, leading to more robust and consistent operator development.

---

#### ✅ Why

- Enforces Kubernetes API best practices
- Helps users catch issues early
- Useful for both maintainers and contributors

---

#### ⚙️ What

1. **Update Kubebuilder’s `.golangci.yml`**  
   Add `kube-api-linter` to:  
   https://github.com/kubernetes-sigs/kubebuilder/blob/master/.golangci.yml

2. **Update the scaffolding logic**  
   - Add linter config to scaffolded `.golangci.yml`
   - See:  
     [`golangci.go`](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go)  
     [`init.go` lines 181–183](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v4/scaffolds/init.go#L181-L183)
   - Likely need a new template for the custom linter config block

3. **Regenerate after changes**  
   ```bash
   make install
   make generate
   ```

---

#### ➕ Pros

- Adds value immediately
- Aligns scaffolded projects with Kubernetes API standards
- Maintained under kubernetes-sigs → better trust/adoption
- Low risk (can be removed if needed; doesn't affect runtime behavior)

---

#### ➖ Cons

- Adds an extra dependency
- May require tuning over time
- We generally aim to limit third-party dependencies to reduce long-term maintenance burden

---

### 🎯 Goal

- [ ] Create a PR
- [ ] Analyze pros and cons in the PR thread
- [ ] Check if our sample projects pass/fail with the linter
- [ ] Fix violations if any
- [ ] Evaluate again whether it’s worth merging based on the trial

**Even if we decide not to adopt it, this effort will still help us identify and possibly fix latent API issues.**

---

**Reference**: https://golangci-lint.run/contributing/new-linters/

**Comment by camilamacedo86** [comment]
@sbueringer @joelspeed @guettli

**Comment by afzal442** [comment]
@camilamacedo86 I take this up!

**Comment by camilamacedo86** [comment]
We did an experimental usage internally, and you can take a look at the PR for more details. 
-> https://github.com/kubernetes-sigs/kubebuilder/pull/4887

The purpose of the project is very cool 🎉 and could be very beneficial for the community. However, it’s not quite mature enough yet for us to add it to the Kubebuilder scaffolds.

- 1. The project currently has no official releases.
- 2. I’ve opened a couple of issues here: https://github.com/kubernetes-sigs/kube-api-linter/issues?q=is%3Aissue%20state%3Aopen%20author%3Acamilamacedo86
- 3. Looking through the existing issues, we can see many useful checks are planned, which is great to see.
- 4. I could not make it work with golangci github action: https://github.com/kubernetes-sigs/kubebuilder/actions/runs/15901556991/job/44845553251?pr=4887 we would need to see if that is possible, To add in the default scaffold that must work too. 

So, once the project becomes more mature, we can definitely revisit this idea and evaluate adding it to the default scaffold. 🙂

c/c @JoelSpeed

**Comment by JoelSpeed** [comment]
> The project currently has no official releases.

There are definitely a few changes I want to get through in terms of the way the project is organised which I'd expect to get in before an initial release, so we can keep an eye on this.

> I’ve opened a couple of issues here

I actually believe both of the current open issues are behaving as expected

> I could not make it work with golangci github action

There are two modes, module and plugin. The plugin mode is preferred, but requires that the golangci-lint binary and the KAL binary are built in the same environment with the same dependencies, which is not how the golangci github action works, and would need to use something custom to achieve I think. I haven't tried to make them work together. The module approach [in use by cluster api](https://github.com/kubernetes-sigs/cluster-api/blob/7e6b3d8e4c58afca77bddff9256513a59f18fa70/.github/workflows/pr-golangci-lint.yaml#L35) might be a better path forward for Kubebuilder if you are supplying github workflows

**Comment by camilamacedo86** [comment]
Hi @JoelSpeed 
Thank you very much for the reply.

> I actually believe both of the current open issues are behaving as expected

We can speak from there. 

>There are two modes, module and plugin. 

The info in the README is no longer valid with GolangCI 2x
I push a PR with the changes: https://github.com/kubernetes-sigs/kube-api-linter/pull/109
Just to let you know.

**Comment by camilamacedo86** [comment]
Hi @JoelSpeed,

After reviewing the answers and giving it more thought, I’ve changed my mind 😊
I now strongly believe we should definitely add the linter as soon as possible.

Without it, we're not really promoting best practices effectively.

I’ve already started working on it: https://github.com/kubernetes-sigs/kubebuilder/pull/4888
(There’s some effort involved — we need to fix the samples and a few other things.)

I just want to share with you.

**Comment by camilamacedo86** [comment]
Hi @afzal442 

Sorry, I removed the good first issue when I realised that the linter spots many places that require changes, and we will need to discuss one of them. So, it will not be a straightforward change as I imagined previously,

**Comment by afzal442** [comment]
sure! I understood. thanks

**Comment by camilamacedo86** [comment]
### Kubebuilder KPAL Integration Status

**What was done so far**
- All the scaffolded API definitions in tutorial projects were reviewed and updated accordingly. So, projects built with kubebuilder 6.0.0, which should already be promoting those practices
- Several improvements to the tutorial content

**What is missing so that we can add the linter**

- [ ] **Determine best way to install KPAL with GolangCI-Lint v2.x**
  - Attempting dynamic `.so` plugin loading is not working (or I could not make it work ;-) )([example attempt](https://github.com/kubernetes-sigs/kubebuilder/pull/4941/files))
  - Static install via `hack/` + `go install` works well ([see example](https://github.com/kubernetes-sigs/kubebuilder/pull/4888/files#diff-f68745e135a6eda02da0878ff4c872eec167a6b4de76530dcb9defd4e126d298R228-R243)) but introduces complexity

- [ ] **Wait for official KPAL plugin releases**
  - Currently the plugin has no tagged release; we might want to wait the first release to introduce

- [ ] **Finalize remaining tutorial cleanup**
  - Pending changes are tracked in: `<link to PR with tutorial fixes>`

- [ ] **KPAL: Allow optional fields with omitzero**
  - Proposal/WIP fix in progress: https://github.com/kubernetes-sigs/kube-api-linter/pull/115

- [ ] **KPAL: Investigate/resolve false positive bug**
  - Open issue: https://github.com/kubernetes-sigs/kube-api-linter/issues/128

**Comment by camilamacedo86** [comment]
**Latest Status**

We have the config now working: https://github.com/kubernetes-sigs/kubebuilder/pull/4941
But we still needing to address in the linter: https://github.com/kubernetes-sigs/kube-api-linter/issues/128

**Comment by bavarianbidi** [comment]
As I've struggled with KALs default configuration applied on a newly created controller (created via `kubebuilder`) I've ended with the following KAL configuration for now.

```yaml
linters:
  default: none
  enable:
    - kubeapilinter # linter for Kube API conventions
  settings:
    custom:
      kubeapilinter:
        type: module
        description: KAL is the Kube-API-Linter and lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            enable:
              # Ensures arrays of structs have at least one required field
              #
              # When an array contains structs where all fields are optional or unmarked, it becomes difficult to distinguish between different array elements in YAML configurations. This can lead to ambiguous or confusing API definitions.
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#arrayofstruct
              - "arrayofstruct"
              # Ensure comments start with the serialized version of the field name.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#commentstart
              - "commentstart"
              # Ensure conditions have the correct json tags and markers.
              #
              # Conditions are idiomatically the first field within the status struct, and the linter will highlight when the Conditions are not the first field.
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#conditions
              - "conditions"
              # Ensure mutually exclusive markers are not used on the same field
              #
              # See also the 'conditions' rule below with the proposed configuration for CRDs.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#conditions
              - "conflictingmarkers"
              # Ensure fields have either a default value or are required
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#defaultorrequired
              # see also the 'default_vs_required' conflicting markers rule below
              - "defaultorrequired"
              # Ensure default markers are configured correctly
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#defaults
              - "defaults"
              # Ensure there are no exact duplicate markers. for types and fields.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#duplicatemarkers
              - "duplicatemarkers"
              # Ensure only int32 and int64 are used for integers.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#integers
              - "integers"
              # Ensure every field has a json tag.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#jsontags
              - "jsontags"
              # Ensure all strings and arrays have maximum lengths/maximum items.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#maxlength
              - "maxlength"
              # Ensure all strings and arrays have minimum lengths/minimum items.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#minlength
              - "minlength"
              # Bools do not evolve over time, should use enums instead.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#nobools
              - "nobools"
              # Prevents usage of `Duration` types.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#nodurations
              - "nodurations"
              # Ensure floats are not used.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#nofloats
              - "nofloats"
              # Ensure maps are not used.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#nomaps
              - "nomaps"
              # Ensure that types and fields do not have the nullable marker.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#nonullable
              - "nonullable"
              # Prevents usage of 'Timestamp' fields
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#notimestamp
              - "notimestamp"
              # Ensure that all fields marked as optional adhere to being pointers and
              # having the `omitempty` value in their `json` tag where appropriate.
              #
              # Because of struct fields in the CRD, the pointer preference setting below is set to WhenRequired:
              # Linter will suggest to add the pointer to the field only when the field zero value is a valid value
              # for the field. When the field zero value is not a valid value for the field, the linter will suggest
              # to remove the pointer from the field. When the field zero value is not a valid value for the field
              # of type struct, the linter will suggest to add omitzero json tag and to remove the pointer from the field.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#optionalfields
              - "optionalfields"
              # Ensure that every field should be marked as `+optional` or `+required`.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#optionalorrequired
              - "optionalorrequired"
              # Ensure that required fields should not be pointers, and should not have `omitempty`.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#requiredfields
              - "requiredfields"
              # Ensure that all array fields have the appropriate listType markers.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#ssatags
              - "ssatags"
              # Ensure all first-level children fields within a status struct are marked as optional.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#statusoptional
              - "statusoptional"
              # Ensure that root objects that have a `status` field should have a status subresource.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#statussubresource
              - "statussubresource"
              # Ensure that types and fields do not contain more than a single definition of a marker that should only be present once.
              #
              # xref: https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#uniquemarkers
              - "uniquemarkers"
            disable:
              - "*"
          lintersConfig:
            conflictingmarkers:
              conflicts:
                - name: "default_vs_required"
                  sets:
                    - ["default", "kubebuilder:default"]
                    - [
                        "required",
                        "kubebuilder:validation:Required",
                        "k8s:required",
                      ]
                  description: "A field with a default value cannot be required"
            conditions:
              isFirstField: Warn # Conditions are idiomatically the first field within the status struct, and the linter will highlight when the Conditions are not the first field.
              useProtobuf: Forbid # For CRDs, protobuf tags are not necessary.
              usePatchStrategy: Forbid # For CRDs, patchStrategy is not necessary.
            optionalFields:
              pointers:
                preference: WhenRequired
```

Before implementing this configuration, I've raised a question regarding the default-findings in [slack](https://kubernetes.slack.com/archives/C02MRBMN00Z/p1769114342461119).
