### ISSUE TITLE
Generated test/ Code Fails Linter in Scaffolded GitHub Action

### ISSUE THREAD

**Issue by binbashing** [kubernetes-sigs/kubebuilder#4812]
### What happened?

When creating a new project and API using `kubebuilder`, the scaffolded test code under `test/` fails lint checks in the default GitHub Actions `Lint` workflow (which is also scaffolded by Kubebuilder). This happens immediately after project initialization and before any user edits.

---

### How can we reproduce it (as minimally and precisely as possible)?

```bash
kubebuilder init --domain example.com --repo example.com/memcached-operator
kubebuilder create api --group cache --version v1 --kind Memcached --resource --controller
go mod tidy
```

Then commit and push to GitHub. The generated `Lint` GitHub Action runs this:

```yaml
name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '~1.22'
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
```

---

### What did you expect to happen?

That all scaffolded code (including under `test/`) would pass the linter, since it’s intended to be a working, ready-to-use project.

---

### What actually happened?

The GitHub Action fails due to linter violations in `test/`, including:

```
test/utils/utils.go:95:36: unnecessary conversion (unconvert)
test/utils/utils.go:156:36: unnecessary conversion (unconvert)
test/e2e/e2e_test.go:281:30: unnecessary conversion (unconvert)
test/e2e/e2e_test.go:96:38: printf: non-constant format string in call to fmt.Fprintf (govet)
test/e2e/e2e_test.go:98:38: printf: non-constant format string in call to fmt.Fprintf (govet)
test/e2e/e2e_test.go:105:38: printf: non-constant format string in call to fmt.Fprintf (govet)
```

These issues are generated automatically and not the result of any user code.

---

### Anything else we need to know?

* Occurs on a brand-new repo with no custom edits.
* The offending code is in `test/` files generated by Kubebuilder.
* Linter version (`v1.61`) and Go version (`1.22`) are from Kubebuilder’s own GitHub Action template.
* I would like to contribute a PR to fix this.

---

### Environment

* **Kubebuilder version**: 4.3.1
* **Go version**: go1.24.2
* **OS**: Ubuntu 22.04
* **GitHub Action**: `golangci-lint-action@v6` (v1.61)

---

### Proposed Fix

Update the test scaffold templates to:

* Avoid unnecessary type conversions (e.g., `string(output)`)
* Avoid passing non-constant format strings to `fmt.Fprintf`
* Ensure compatibility with default `golangci-lint` rules
