### ISSUE TITLE
Resources fields with underscore in json tag is not added to the CRD definition 

### ISSUE THREAD

**Issue by vivekzhere** [kubernetes-sigs/kubebuilder#490]
```
type SloopSpec struct {
  Foo string `json:"foo_field"`
  Bar string `json:"barfield"`
}
```

is generating a spec like:

```
spec:
  properties:
    barfield:
      type: string
  required:
  - barfield
  type: object
```
