### ISSUE TITLE
Duplicate rbac roles

### ISSUE THREAD

**Issue by s12chung** [kubernetes-sigs/kubebuilder#558]
when placing two different comments for the same resource, I get duplicate/overlaying rbac roles.

ex:
```go
// +kubebuilder:rbac:groups="",resources=events,verbs=get
// +kubebuilder:rbac:groups="",resources=events,verbs=get,list
```

I get:
```yaml
- apiGroups:
   - ""
   resources:
   - events
   verbs:
   - get
- apiGroups:
   - ""
   resources:
   - events
   verbs:
   - get
   - list
```

or if i duplicate the comment, I get two entries. I expect the entries to merge together
