### ISSUE TITLE
Getting client-go to work is difficult and error-prone

### ISSUE THREAD

**Issue by yanniszark** [kubernetes-sigs/kubebuilder#566]
For my project, I need to use an uncached client for multiple reasons:
1. Dynamic client doesn't support patch
2. I don't want the overhead of the caching since I do very little reads.

* **What went wrong:**

I imported client-go into my project, ran `dep ensure -v` and got this weird error:
```
vendor/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go:46:32: feature.DefaultFeatureGate.Add undefined (type feature.FeatureGate has no field or method Add)
```

I then remembered that in many projects, versions of client-go and kubernetes components are pinned to ensure compatibility. 
However, `controller-runtime` also uses client-go, so we need to specify the same versions as controller-runtime uses. 

* **How I fixed it:**
1. Updated the controller-runtime constraint from v0.1.1 to v0.1.9
2. Checked the controller-runtime v0.1.9 Gopkg.toml and saw it used version v1.12.3 of the kubernetes/client-go packages
3. Added the following to my project's Gopkg.toml
```toml
[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.12.3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.3"
```

kubebuilder should provide an easy way for the user to utilize the client-go package for an uncached client or at least document how to do so. The above procedure is very painful to diagnose and resolve.
