### ISSUE TITLE
Use items as tag

### ISSUE THREAD

**Issue by zlcnju** [kubernetes-sigs/kubebuilder#635]
```
 validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            arguments:
              items:#(which represents a json tag)
                properties:
                  items:
                    description: Items contains all argument for templates
                    items:
                      properties:
                        name:
                          description: Name is the name of a PipelineTemplate
                          type: string
                      type: object
                    type: array
                type: object
              type: array
```

I use the struct define in another projects, however , it use the "items" as it's json tag. When i use kubebuilder, i find items represent an array. This make a conflict in the above crd yaml. Anynoe could provide me a solution.

The struct in my the other project look likes 
```
type A struct {
	Items []B `json:"items"`
}
```
My project with kubebuilder 
```
type C struct {
	Arguments      []A `json:"arguments,omitempty"`
}

```
