### ISSUE TITLE
Kubebuilder generated openapi spec does not respect OpenAPISchemaType() method

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/kubebuilder#645]
My CRD has a field of type resource.Quantity. The openapi type should be string instead it is generated as object. This is causing validation error.

```
CPU         *resource.Quantity `json:"cpu"`
```

```
        spec:
          properties:
            cpu:
              type: object
```

https://github.com/kubernetes/apimachinery/blob/03ac7a9ade429d715a1a46ceaa3724c18ebae54f/pkg/api/resource/quantity.go#L389

/kind bug
