### ISSUE TITLE
kubectl apply -f samples error

### ISSUE THREAD

**Issue by pytimer** [kubernetes-sigs/kubebuilder#646]
Hi, all

I use `kubebuilder` create CRD, now i have a question.

I already create api, and it successfully. i run `make install`  to generate CRD for my remote Kubernetes cluster, it also successfully. But when i want to create samples, it failed.

`kubectl apply -f config/samples/cloud_v1beta1_nodepool.yaml` return error: `error: unable to recognize "config/samples/cloud_v1beta1_nodepool.yaml": no matches for kind "NodePool" in version "cloud.pytimer.io/v1beta1"`

Kubernetes version: `v1.11.6`

My crds.yaml:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: nodepools.cloud.pytimer.io
spec:
  group: cloud.pytimer.io
  names:
    kind: NodePool
    plural: nodepools
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

My sample.yaml is:

```yaml
apiVersion: cloud.pytimer.io/v1beta1
kind: NodePool
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: nodepool-sample
spec:
  # Add fields here
  foo: bar
```

I don't know why. I am a beginner for CRD.
