### ISSUE TITLE
[feature request] Support running tests in Docker container natively

### ISSUE THREAD

**Issue by gaocegege** [kubernetes-sigs/kubebuilder#665]
/kind feature

Now we generated some test cases and can run the test locally. While when we want to run the test in some Docker-based CI systems, for example, https://github.com/caicloud/cyclone or https://github.com/drone/drone, we need to install kubebuilder first then `make test`.

I'd appreciate if we could maintain a docker image for the unit test in kubebuilder community.

**Comment by mengqiy** [comment]
@gaocegege Looking at the `test` target in the generated `Makefile`, it seems the things you need in your image are go toolchains. Nothing requires kubebuilder to run the tests actually.
You can try to use golang docker image, it should work.

**Comment by gaocegege** [comment]
@mengqiy It does not work, actually. We need to install kubebuilder(precisely, apiserver and etcd in kubebuilder bin). Or the test cannot be run.

**Comment by mengqiy** [comment]
I see. You need apiserver, etcd and go toolchain in the image to run the tests.
We will need to maintain an image for each k8s minor versions.

**Comment by afirth** [comment]
I'm sure I'll find some edge cases when versions don't line up, but here's my hack to get something  working. Based on the kustomize GCB image. I don't remember why I didn't build kustomize from source - possibly there was a good reason, possibly I just started there an then realized it didn't have go :D

`cat kubebuilder-image/Dockerfile`
```
# https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/kustomize
FROM gcr.io/<REPLACEME>/kustomize:3.1.0 as builder
# provides kustomize binaries to copy

ARG KUBEBUILDER_VERSION=2.0.0-alpha.4

RUN echo ${KUBEBUILDER_VERSION}
RUN curl -sL# https://go.kubebuilder.io/dl/${KUBEBUILDER_VERSION}/linux/amd64 | tar -xz -C /builder/
RUN mv /builder/kubebuilder_${KUBEBUILDER_VERSION}_linux_amd64 /builder/kubebuilder

FROM gcr.io/cloud-builders/go
ARG CONTROLLER_GEN_VERSION=v0.2.0-beta.2
# copy kustomize
COPY --from=builder /builder/kustomize /builder/kustomize
ENV PATH=/builder/kustomize:$PATH
# copy kubebuilder
# test scripts require this to be in usr/local
COPY --from=builder /builder/kubebuilder /usr/local/kubebuilder
ENV PATH=/usr/local/kubebuilder/bin:$PATH

#install controller-gen
ENV GO111MODULE=on
RUN go get sigs.k8s.io/controller-tools/cmd/controller-gen@${CONTROLLER_GEN_VERSION}
ENV PATH=/go/bin:$PATH

ENTRYPOINT make
```

`cat kubebuilder-image/cloudbuild.yaml `
```
steps:
- name: gcr.io/kaniko-project/executor
  id: image-build
  args:
  - --destination=gcr.io/$PROJECT_ID/$_IMG_NAME:$SHORT_SHA
  - --destination=gcr.io/$PROJECT_ID/$_IMG_NAME:latest
  - --cache=true
  - --cache-ttl=2h
  - --build-arg
  - KUBEBUILDER_VERSION=${_KUBEBUILDER_VERSION}
  - --build-arg
  - CONTROLLER_GEN_VERSION=${_CONTROLLER_GEN_VERSION}
  - --destination=gcr.io/$PROJECT_ID/$_IMG_NAME:${_KUBEBUILDER_VERSION}

substitutions:
  _KUBEBUILDER_VERSION: 2.0.0-beta.0
  _CONTROLLER_GEN_VERSION: v0.2.0-beta.4
  _IMG_NAME: kubebuilder
```

This will build an push a kubebuilder image which can be used in other places like so:

`cat mycontroller/deploy/cloudbuild.yaml`
```
steps:

  # Build and Test the go packages and boilerplate
- name: gcr.io/$PROJECT_ID/kubebuilder:2.0.0-alpha.4
  id: go-build
  waitFor: ['-'] #parallel
  entrypoint: make
  args: ['test', 'all']
```


Hope that helps someone
