### ISSUE TITLE
conversion webhook service namespace is not replaced by kustomize

### ISSUE THREAD

**Issue by youyongsong** [kubernetes-sigs/kubebuilder#820]
kubebuilder scaffold a patch `crd/patches/webhook_in_<resource>s.yaml` like this:
```yaml
# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusters.clusterregistry.k8s.io
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      # this is "\n" used as a placeholder, otherwise it will be rejected by the apiserver for being blank,
      # but we're going to set it later using the cert-manager (or potentially a patch if not using cert-manager)
      caBundle: Cg==
      service:
        namespace: system
        name: webhook-service
        path: /convert
```
I want to replace all resources' namespace in `default/kustomization.yaml` like this:
```yaml
namespace: test-system
namePrefix: cluster-registry-
```
Then I run `kustomize build config/default > deploy.yaml` to generate the final yaml, all resources' namespace had been replaced with `test-system` except `spec.conversion.webhookClientConfig.service.namespace`:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    certmanager.k8s.io/inject-ca-from: alauda-system/cluster-registry-serving-cert
  creationTimestamp: null
  labels:
    app: cluster-registry-manager
  name: clusters.clusterregistry.k8s.io
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      caBundle: Cg==
      service:
        name: cluster-registry-webhook-service
        namespace: system
        path: /convert
```

Is this a bug of kubebuilder or kustomize?
/kind bug
